with(document) {
write("<div id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:479px;\">");
write("<div id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:479px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/TL19EEB0000000K0081BAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:479px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:15px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:429px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:33px;top:382px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:452px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:451px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:452px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>M, N<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:915px;top:230px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792px;top:451px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:203px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:451px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>M, N<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:68px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:451px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:306px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319px;top:15px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:24px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:268px;top:451px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16px;top:130px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}