with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:417px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:417px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19EAAA20321019461FAAD16.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:417px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:166px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b></b>Terminal side of female terminals <br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77px;top:17px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>PGM-FI MAIN RELAY 1 (ECU) 4P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:212px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>ECM CONNECTOR No. 2 (58P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:386px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b></b>Terminal side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273px;top:66px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>IGP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:234px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>IGP3 (YEL/BLK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257px;top:343px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>IGP1 (YEL/BLK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:246px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>IGP2 <br>(YEL/<br>BLK)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}