with(document) {
write("<div id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\">");
write("<div id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/TL19ED0000000000000EBA209.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:766px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:879px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:791px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:684px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:51px;top:791px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:766px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:684px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:743px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(1.4 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:736px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LIGHT <br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:619px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:645px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>106<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:645px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>149<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:822px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>382<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:602px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:645px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>287<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:602px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:602px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-18px;top:602px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-22px;top:619px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-44px;top:645px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>330<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:595px;top:512px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:512px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:698px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:786px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506px;top:879px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:766px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575px;top:786px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:572px;top:879px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:717px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:628px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:628px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:677px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:677px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575px;top:609px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353px;top:698px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353px;top:786px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:351px;top:879px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:766px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:786px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:717px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:628px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:628px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:677px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:677px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:609px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575px;top:839px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:512px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:538px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>173<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:538px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>167<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:576px;top:539px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>103<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:736px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CIGARETTE <br>LIGHTER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:843px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(In the gauge <br>control module) <br>(12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-168px;top:731px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SECURITY <br>HORN <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-174px;top:822px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SECURITY <br>HORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-262px;top:842px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>MICU <br>(14−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:619px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A) <br>FUSE <br>(4−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-268px;top:548px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 10 (10 A) <br>FUSE <br>(1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:619px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CIGARETTE <br>LIGHTER RELAY <br>(2−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:619px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CIGARETTE <br>LIGHTER RELAY <br>(6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-171px;top:548px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 10 (10 A) <br>FUSE <br>(5−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-56px;top:619px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A) <br>FUSE <br>(8−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-359px;top:842px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>MICU <br>(16−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 18 (7.5 A) <br>FUSE <br>(2−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 16 (20 A) <br>FUSE <br>(4−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:642px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CONSOLE <br>ACCESSORY <br>POWER SOCKET <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:731px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CONSOLE <br>ACCESSORY <br>POWER <br>SOCKET<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:642px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CARGO AREA <br>ACCESSORY <br>POWER SOCKET <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:731px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CARGO AREA <br>ACCESSORY <br>POWER <br>SOCKET<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 12 (20 A) <br>FUSE <br>(4−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390px;top:184px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:250px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:250px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:265px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:265px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:265px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:298px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VOLTAGE REGULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:442px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RECTIFIER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:250px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:250px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:265px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:283px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:283px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:283px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:460px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ALTERNATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:210px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>91<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:210px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p2_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:167px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495px;top:167px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:210px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>273<br></b></nobr>");
write("</p>");
write("<p id=\"p2_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:184px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:163px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:163px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:184px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:35px;top:210px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>211<br></b></nobr>");
write("</p>");
write("<p id=\"p2_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:184px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:640px;top:184px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:210px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>370<br></b></nobr>");
write("</p>");
write("<p id=\"p2_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:379px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>379<br></b></nobr>");
write("</p>");
write("<p id=\"p2_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:219px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>375<br></b></nobr>");
write("</p>");
write("<p id=\"p2_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:210px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>374<br></b></nobr>");
write("</p>");
write("<p id=\"p2_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:184px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 7 (15 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:187px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM <br>(10−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:185px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 7 (15 A) <br>FUSE <br>(6−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120px;top:177px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 1 (MAIN) <br>(100 A) <br>FUSE <br>(1−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:177px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 1 (MAIN) <br>(100 A) <br>FUSE <br>(5−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-239px;top:118px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IGNITION <br>SWITCH <br>(3−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-160px;top:118px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IGNITION <br>SWITCH <br>(7−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:184px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 16 (7.5 A) <br>FUSE <br>(8−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:399px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>MICU <br>(16−D)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}