with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1071px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E20A14100012901LAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ROTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:114px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BEARING RETAINER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:150px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT BEARING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:187px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DRIVE END HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791px;top:578px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PULLEY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:1044px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REAR HOUSING ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46px;top:794px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HEAT SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:874px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>END COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:948px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BRUSH HOLDER<br>ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781px;top:314px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PULLEY LOCKNUT<br>110 N·m <br>(11.2 kgf·m, 81.0 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:63px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>2.3 N·m <br>(0.23 kgf·m, 1.7 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:239px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1.0 mm<br>10.0 N·m <br>(1.02 kgf·m, 7.4 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329px;top:1027px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>5.9 N·m <br>(0.61 kgf·m, 4.4 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:522px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1.0 mm<br>10.0 N·m <br>(1.02 kgf·m, 7.4 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:523px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>4.5 N·m <br>(0.46 kgf·m, 3.3 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:613px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1.8 N·m <br>(0.18 kgf·m, 1.3 lbf·ft)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}