with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1071px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E20A18300000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:18px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BLANCER SHAFT/BALANCER<br>SHAFT HOLDER ASSEMBLY<br><a href=\"javascript:CtsProc('0','000000000001113','iR01')\"></b>Removal,</a><br><a href=\"javascript:CtsProc('0','000000000001113','iR02')\">Inspection,</a><br><a href=\"javascript:CtsProc('0','000000000001113','iR03')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:123px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>O-RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:696px;top:499px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DOWEL PIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707px;top:646px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CRANKSHAFT<br><a href=\"javascript:CtsProc('0','000000000001114','i000')\"></b>End Play,</a><br><a href=\"javascript:CtsProc('0','000000000001119','iT02')\">Runout,</a><br><a href=\"javascript:CtsProc('0','000000000001119','i000')\">Out-of-Round,</a><br><a href=\"javascript:CtsProc('0','000000000001117','i000')\">Removal,</a><br><a href=\"javascript:CtsProc('0','000000000001118','i000')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707px;top:874px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>KNOCK SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654px;top:906px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MAIN BEARINGS<br><a href=\"javascript:CtsProc('0','000000000001120','i000')\"></b>Oil Clearance,</a><br><a href=\"javascript:CtsProc('0','000000000001120','iR02')\">Selection,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:892px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>THRUST WASHERS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:710px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CKP PULSE PLATE<br><a href=\"javascript:CtsProc('0','000000000001121','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:6px;top:582px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CRANKSHAFT OIL SEAL,<br>TRANSMISSION END<br><a href=\"javascript:CtsProc('0','000000000001118','i220')\"></b>Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:63px;top:319px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LOWER BLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:205px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OIL CONTROL ORIFICE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:126px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>O-RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:126px;top:33px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CRANKSHAFT POSITION<br>(CKP) SENSOR<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}