with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:481px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:481px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E20A18316617502KBAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:481px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:17px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Larger block bore<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:43px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>1 or <br>A or I<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:43px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>2 or <br>B or II<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:43px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>3 or <br>C or III<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:43px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>4 or <br>D or IIII<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:85px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Smaller bearing (Thicker)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:389px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Blue<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:190px;top:133px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Pink<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:190px;top:287px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:235px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:277px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Green/<br>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:226px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Green/<br>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:287px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:123px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Yellow/<br>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:235px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:278px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Brown/<br>Black<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:27px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Crank <br>bore <br>code<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:57px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Main <br>journal <br>code<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:133px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:184px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:235px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:287px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:338px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:389px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:425px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Smaller<br>main<br>journal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120px;top:425px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Smaller<br>bearing<br>(Thicker)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:123px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Pink/<br>Yellow<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:132px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Yellow<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:175px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Yellow/<br>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:388px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Black<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:381px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Black/<br>Blue<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:190px;top:226px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Yellow/<br>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:379px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Brown/<br>Black<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:190px;top:182px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Yellow<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:184px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:175px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Green/<br>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:329px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Black/<br>Blue<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:338px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Black<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:328px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Brown/<br>Black<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:190px;top:336px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Brown<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}