with(document) {
write("<div id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\">");
write("<div id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/TL19EGP000000000000EBA322.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-93px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-40px;top:604px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-43px;top:879px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:604px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:879px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G901<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-40px;top:822px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:822px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16px;top:649px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16px;top:822px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:26px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:26px;top:779px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14px;top:879px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G505<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-28px;top:711px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-28px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:711px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-40px;top:649px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-18px;top:627px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:560px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>472<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-40px;top:561px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>409<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:879px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G901<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:604px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:604px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:604px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:879px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:604px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:444px;top:879px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G901<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:822px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:822px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:822px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:822px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:879px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G302<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:879px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274px;top:779px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:822px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:604px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:649px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:822px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:779px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:879px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G505<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:795px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:711px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:711px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:711px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:711px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:649px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:477px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:560px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>475<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:560px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>474<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:560px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>411<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:561px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>410<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:560px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>473<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:649px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-443px;top:780px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT <br>BACK−UP <br>LIGHT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-368px;top:780px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>BACK−UP <br>LIGHT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-399px;top:628px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 5 (7.5 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-301px;top:628px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 5 (7.5 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-399px;top:512px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 5 (7.5 A) <br>FUSE <br>(6−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-301px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 5 (7.5 A) <br>FUSE <br>(8−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-186px;top:747px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT <br>REAR <br>TURN <br>SIGNAL <br>LIGHT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:747px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>REAR <br>TURN <br>SIGNAL <br>LIGHT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-151px;top:747px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT <br>FRONT <br>TURN <br>SIGNAL <br>LIGHT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-80px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT <br>SIDE <br>TURN <br>SIGNAL <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-80px;top:780px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT <br>POWER <br>MIRROR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:780px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>POWER <br>MIRROR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>SIDE <br>TURN <br>SIGNAL <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-75px;top:536px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S MICU<br>(16−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT <br>REAR <br>TURN <br>SIGNAL <br>LIGHT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>REAR <br>TURN <br>SIGNAL <br>LIGHT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT <br>FRONT <br>TURN <br>SIGNAL <br>LIGHT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>FRONT <br>TURN <br>SIGNAL <br>LIGHT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT <br>SIDE <br>TURN <br>SIGNAL <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:780px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT <br>POWER <br>MIRROR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:780px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>POWER <br>MIRROR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>SIDE <br>TURN <br>SIGNAL <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:536px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S MICU<br>(18−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-581px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HIGH <br>MOUNT <br>BRAKE <br>LIGHT <br>(LED x 12)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p3_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:87px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:87px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:72px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:79px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:79px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:72px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:79px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:87px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:72px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:94px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:94px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:94px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>With automatic lighting system<br></b></nobr>");
write("</p>");
write("<p id=\"p3_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-125px;top:473px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(RHD model)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:108px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:108px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:101px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:101px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:101px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Without automatic lighting system<br></b></nobr>");
write("</p>");
write("<p id=\"p3_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:108px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p3_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:115px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:115px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:115px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p3_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:265px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:272px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:219px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:303px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:229px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:229px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432px;top:158px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:219px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:158px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:303px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:340px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-40px;top:340px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-40px;top:282px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:365px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:35px;top:263px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-57px;top:263px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-49px;top:365px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-49px;top:396px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>397<br></b></nobr>");
write("</p>");
write("<p id=\"p3_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:427px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>480<br></b></nobr>");
write("</p>");
write("<p id=\"p3_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-23px;top:83px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-23px;top:176px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-47px;top:219px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>86<br></b></nobr>");
write("</p>");
write("<p id=\"p3_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-28px;top:193px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:409px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:427px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>58<br></b></nobr>");
write("</p>");
write("<p id=\"p3_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:409px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:427px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>396<br></b></nobr>");
write("</p>");
write("<p id=\"p3_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:409px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:376px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:427px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>481<br></b></nobr>");
write("</p>");
write("<p id=\"p3_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:409px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:427px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>243<br></b></nobr>");
write("</p>");
write("<p id=\"p3_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:409px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:427px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>396<br></b></nobr>");
write("</p>");
write("<p id=\"p3_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:409px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:376px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-49px;top:126px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>265<br></b></nobr>");
write("</p>");
write("<p id=\"p3_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-28px;top:100px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:83px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:176px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:219px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:193px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:126px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>198<br></b></nobr>");
write("</p>");
write("<p id=\"p3_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:100px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412px;top:334px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>387<br></b></nobr>");
write("</p>");
write("<p id=\"p3_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:334px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>416<br></b></nobr>");
write("</p>");
write("<p id=\"p3_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:184px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>135<br></b></nobr>");
write("</p>");
write("<p id=\"p3_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412px;top:184px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>148<br></b></nobr>");
write("</p>");
write("<p id=\"p3_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353px;top:407px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:427px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>417<br></b></nobr>");
write("</p>");
write("<p id=\"p3_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:141px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:141px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:141px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:141px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:158px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:158px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:239px;top:184px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>311<br></b></nobr>");
write("</p>");
write("<p id=\"p3_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:184px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>321<br></b></nobr>");
write("</p>");
write("<p id=\"p3_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:282px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-461px;top:366px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>FRONT <br>POSITION <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-324px;top:365px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LICENSE  <br>PLATE <br>LIGHT <br>(5 W x 2)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-204px;top:365px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>TAILLIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-284px;top:365px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT <br>TAILLIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-124px;top:366px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT <br>FRONT <br>POSITION <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-386px;top:193px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>MICU<br>(18−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-391px;top:100px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 27 (10 A) <br>FUSE <br>(7−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-222px;top:193px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>MICU<br>(18−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-227px;top:100px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 27 (10 A) <br>FUSE <br>(7−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-368px;top:366px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>FRONT <br>POSITION <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-151px;top:193px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S <br>MICU<br>(19−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-144px;top:100px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 2 (10 A) <br>FUSE <br>(8−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:257px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HAZARD <br>WARNING <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:354px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(In the gauge <br>control module) <br>(14−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:158px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A) <br>FUSE <br>(4−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:158px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 9 (15 A) <br>FUSE <br>(3−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:354px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>MICU<br>(16−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:35px;top:447px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>MICU <br>(16−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:341px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRAKE PEDAL <br>POSITION <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-57px;top:417px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PCM <br>(10−D) (12−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-60px;top:193px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 7 (15 A) <br>FUSE <br>(2−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75px;top:447px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC <br>RELAY <br>(2−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:110px;top:447px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PCM <br>(10−D) <br>(12−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185px;top:447px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>MICU <br>(18−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:447px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC <br>RELAY <br>(6−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-60px;top:100px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 7 (15 A) <br>FUSE <br>(6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:301px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(Open: <br>Brake pedal released) <br>(Closed: <br>Brake pedal pressed)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:29px;top:193px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 12 (15 A) <br>FUSE <br>(1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:29px;top:100px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 12 (15 A) <br>FUSE <br>(5−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:447px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>MICU<br>(18−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:158px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A) <br>FUSE <br>(8−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:158px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 9 (15 A) <br>FUSE <br>(7−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:447px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PCM <br>(10−D) <br>(12−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-244px;top:365px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT <br>INNER <br>TAILLIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-164px;top:365px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>INNER <br>TAILLIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}