with(document) {
write("<div id=\"group5\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect5\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img5\" name=\"PrtImgId\" src=\"../img/TL19E20A20300000000EAAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p5_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792px;top:390px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE D<br></b></nobr>");
write("</p>");
write("<p id=\"p5_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:591px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:500px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B44<br></b></nobr>");
write("</p>");
write("<p id=\"p5_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:508px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:673px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:582px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B35<br></b></nobr>");
write("</p>");
write("<p id=\"p5_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:664px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B25<br></b></nobr>");
write("</p>");
write("<p id=\"p5_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:820px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:810px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B17<br></b></nobr>");
write("</p>");
write("<p id=\"p5_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:974px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:964px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>C43<br></b></nobr>");
write("</p>");
write("<p id=\"p5_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:750px;top:558px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A/T CLUTCH PRESSURE<br>CONTROL SOLENOID VALVE A<br></b></nobr>");
write("</p>");
write("<p id=\"p5_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:750px;top:641px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A/T CLUTCH PRESSURE<br>CONTROL SOLENOID VALVE B<br></b></nobr>");
write("</p>");
write("<p id=\"p5_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:751px;top:725px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A/T CLUTCH PRESSURE<br>CONTROL SOLENOID VALVE C<br></b></nobr>");
write("</p>");
write("<p id=\"p5_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791px;top:871px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>INPUT SHAFT<br>(MAINSHAFT)<br>SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:695px;top:852px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:695px;top:787px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:619px;top:740px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p5_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792px;top:1025px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>OUTPUT SHAFT<br>(COUNTERSHAFT)<br>SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:696px;top:941px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:619px;top:894px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p5_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:696px;top:1006px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765px;top:934px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:502px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:965px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:998px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p5_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:517px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LSA<br></b></nobr>");
write("</p>");
write("<p id=\"p5_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:599px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LSB<br></b></nobr>");
write("</p>");
write("<p id=\"p5_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:681px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LSC<br></b></nobr>");
write("</p>");
write("<p id=\"p5_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:827px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>NM<br></b></nobr>");
write("</p>");
write("<p id=\"p5_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:982px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>NC<br></b></nobr>");
write("</p>");
write("<p id=\"p5_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:94px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B27<br></b></nobr>");
write("</p>");
write("<p id=\"p5_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:103px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:167px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B10<br></b></nobr>");
write("</p>");
write("<p id=\"p5_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:175px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:230px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B11<br></b></nobr>");
write("</p>");
write("<p id=\"p5_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:239px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:138px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ATF TEMPERATURE<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:60px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p5_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:102px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:120px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792px;top:201px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE A<br></b></nobr>");
write("</p>");
write("<p id=\"p5_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:175px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792px;top:264px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE B<br></b></nobr>");
write("</p>");
write("<p id=\"p5_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:238px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:120px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:95px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p5_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:111px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ATFT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:184px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SHA<br></b></nobr>");
write("</p>");
write("<p id=\"p5_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:247px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SHB<br></b></nobr>");
write("</p>");
write("<p id=\"p5_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:292px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B20<br></b></nobr>");
write("</p>");
write("<p id=\"p5_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237px;top:302px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792px;top:327px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE C<br></b></nobr>");
write("</p>");
write("<p id=\"p5_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:301px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:310px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SHC<br></b></nobr>");
write("</p>");
write("<p id=\"p5_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:355px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B26<br></b></nobr>");
write("</p>");
write("<p id=\"p5_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:364px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:364px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:372px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SHD<br></b></nobr>");
write("</p>");
write("<p id=\"p5_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:531px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:584px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:614px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:666px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:696px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:539px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:621px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:703px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:699px;top:764px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p5_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:112px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p5_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:168px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p5_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:227px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:290px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:354px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p5_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765px;top:779px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:811px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:844px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p5_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:895px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p5_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791px;top:452px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE E<br></b></nobr>");
write("</p>");
write("<p id=\"p5_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:418px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B24<br></b></nobr>");
write("</p>");
write("<p id=\"p5_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:427px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:427px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:435px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SHE<br></b></nobr>");
write("</p>");
write("<p id=\"p5_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:417px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p5_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:675px;top:63px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>8P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:1037px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>*1: A/T<br></b></nobr>");
write("</p>");
write("<p id=\"p5_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:51px;top:46px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}