with(document) {
write("<div id=\"group18\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\">");
write("<div id=\"rect18\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img18\" name=\"PrtImgId\" src=\"../img/TL19EGPJ54230100000EAAD18.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p18_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:27px;top:28px;font-weight:normal;font-size:9.14pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p18_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:590px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p18_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:589px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p18_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:590px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p18_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293px;top:362px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p18_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:361px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p18_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:276px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p18_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:319px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p18_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:276px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p18_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:319px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p18_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82px;top:533px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G901<br></b></nobr>");
write("</p>");
write("<p id=\"p18_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293px;top:419px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p18_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:419px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p18_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:276px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left brake light/taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p18_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:291px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p18_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:334px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right rear turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p18_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:319px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right brake light/taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p18_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:419px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>License plate lights<br></b></nobr>");
write("</p>");
write("<p id=\"p18_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:476px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right back−up light (Without rear fog light)<br></b></nobr>");
write("</p>");
write("<p id=\"p18_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:462px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left back−up light<br></b></nobr>");
write("</p>");
write("<p id=\"p18_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:491px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear fog light<br></b></nobr>");
write("</p>");
write("<p id=\"p18_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:612px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AG<br></b></nobr>");
write("</p>");
write("<p id=\"p18_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:610px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p18_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:612px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Tailgate wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p18_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:190px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p18_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:190px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p18_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:104px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p18_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:147px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p18_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:104px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p18_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:147px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p18_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:233px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p18_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:233px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p18_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:61px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p18_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:61px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p18_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:62px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power talgate unit (PG1)<br></b></nobr>");
write("</p>");
write("<p id=\"p18_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:105px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power talgate unit (PG2)<br></b></nobr>");
write("</p>");
write("<p id=\"p18_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:148px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power talgate unit (SG)<br></b></nobr>");
write("</p>");
write("<p id=\"p18_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:191px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Drive unit<br></b></nobr>");
write("</p>");
write("<p id=\"p18_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:233px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power talgate outside beeper<br></b></nobr>");
write("</p>");
write("<p id=\"p18_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:519px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right inner taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p18_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:505px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left inner taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p18_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:534px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear wiper motor<br></b></nobr>");
write("</p>");
write("<p id=\"p18_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:548px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear window defogger (−) terminal<br></b></nobr>");
write("</p>");
write("<p id=\"p18_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:562px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>High mount brake light<br></b></nobr>");
write("</p>");
write("<p id=\"p18_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:361px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p18_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:419px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p18_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426px;top:362px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AG<br></b></nobr>");
write("</p>");
write("<p id=\"p18_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426px;top:419px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AG<br></b></nobr>");
write("</p>");
write("<p id=\"p18_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:361px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Tailgate latch switch <br>(Without power tailgate)<br></b></nobr>");
write("</p>");
write("<p id=\"p18_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:390px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Tailgate outer handle switch <br>(Without power tailgate)<br></b></nobr>");
write("</p>");
write("<p id=\"p18_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:433px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Tailgate relrease actuator <br>(Without power tailgate)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}