with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:1900px; height:1108px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:1900px;height:1108px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E40J20100000000LEAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:1900px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:391px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>a1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:496px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>c2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448px;top:502px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>c3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:511px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>e1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:627px;top:513px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>g3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:391px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>c1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:355px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>f2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:513px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>f1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:354px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>a2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:350px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>b<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:618px;top:354px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>g1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:721px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>d1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:699px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>d2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495px;top:692px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>d3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520px;top:673px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>d4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:515px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>e2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544px;top:409px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>g2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:354px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>g4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:348px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>h1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:852px;top:347px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>i1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1082px;top:340px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>h2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1140px;top:337px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>i2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1225px;top:330px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>j<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1278px;top:328px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>k<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1341px;top:329px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>l1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1406px;top:329px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>m<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1523px;top:329px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>l2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1582px;top:329px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1671px;top:331px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>p<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1474px;top:329px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>n1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1445px;top:851px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>n2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157px;top:591px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>CENTER<br>LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583px;top:1036px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>BASE <br>LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:201px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>505 (19.9) a1, b1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496px;top:219px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>384 (15.12) c1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496px;top:238px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>383 (15.08) c2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:833px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>29 (1.14) g2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:870px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>133 (5.24) d3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:889px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>177 (6.97) d2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:907px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>267 (10.5) d1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720px;top:871px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>142 (5.59) f2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:627px;top:889px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>365 (14.4) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:908px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>775 (30.5) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1025px;top:238px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>1650 (64.96) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1007px;top:911px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>1445 <br>(56.89) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:619px;top:325px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>14 (0.55) g1, g3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:640px;top:277px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>425 (16.7) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:258px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>950 (37.4) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1530px;top:146px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>3255 (128.1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1458px;top:164px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>3017 (118.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1417px;top:183px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>2888 (113.7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1362px;top:201px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>2705 (106.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1221px;top:221px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>2250 (88.58)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1539px;top:986px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>3165 <br>(124.6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1419px;top:982px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>2891 (113.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1311px;top:951px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>2424<br>(95.43)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1187px;top:945px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>2145 (84.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:852px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>101 (3.98) d4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:486px;top:263px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>250 <br>(9.84) <br>c3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:276px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>208 (8.19) <br>e1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:310px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>192 (7.56) <br>e2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:839px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>57 <br>(2.24) g4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:553px;top:369px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>f1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542px;top:353px;font-weight:normal;font-size:7.66pt;\">");
write("<nobr><b>111 (4.73)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:57px;top:21px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>Unit: mm (in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:57px;top:41px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>φ: Inner diameter<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:68px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>a1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:91px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>a2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:115px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>b<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:138px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>c1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:68px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For front subframe mount φ20 (0.79) front<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:91px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For front subframe mount φ16 (0.63) rear<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:162px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>c2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:185px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>c3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:209px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>d1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:976px;top:79px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>i2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1012px;top:79px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>Front floor tunnel frame locating hole φ13 (0.51) rear<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:976px;top:103px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>j<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1012px;top:103px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>Rear frame A locating hole φ25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:974px;top:127px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>k<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1012px;top:126px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>Rear floor locating hole φ25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1436px;top:56px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>l1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:56px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For rear subframe mount φ26.2 (1.03) front<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1436px;top:80px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>l2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1436px;top:103px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>m<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:103px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>Rear damper center hole φ52 (2.05)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:973px;top:1040px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>n1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1012px;top:1040px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>Rear floor cross-member locating hole φ15 (0.59) right side<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:973px;top:1064px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>n2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1499px;top:1039px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1498px;top:1063px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>p<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:957px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>g1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:980px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>g2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:1003px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>g3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:1027px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>g4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:1050px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>h1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:957px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>Front damper center hole φ50 (1.97) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:980px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For front damper mount φ11.5 (0.45) front <br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:1004px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For front damper mount φ11.5 (0.45) center side<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:1027px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For front damper mount φ11.5 (0.45) rear<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:1050px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>Front floor locating hole φ25 (0.98) front<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:1074px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>Front floor tunnel frame locating hole φ13 (0.51) front<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:1074px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>i1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:138px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For engine side mount φ13 (0.51) front<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:115px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>Front side frame rear end locating hole φ25 (0.98) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:162px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For engine side mount φ13 (0.51) middle<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:185px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For engine side mount φ13 (0.51) rear<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:933px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>f2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:933px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For upper arm mount φ11 (0.43) rear<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:80px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For rear subframe mount φ26.2 (1.03) rear<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1535px;top:1039px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>Rear frame B locating hole φ25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:973px;top:56px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>h2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1012px;top:56px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>Front floor locating hole φ25 (0.98) rear<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1012px;top:1063px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>Rear floor cross-member locating hole φ15 (0.59) left side<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1534px;top:1064px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>Spare tyre pan locating hole φ25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:209px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For transmission mount φ15 (0.59) front<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:910px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>f1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:910px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For upper arm mount φ11 (0.43) front<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:233px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>d2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:280px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>d4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:256px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>d3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:280px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For transmission mount φ15 (0.59) rear<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546px;top:68px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>e1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547px;top:106px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>e2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:256px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For transmission mount φ15 (0.59) middle<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:233px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For transmission mount φ15 (0.59) upper<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:585px;top:68px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For torque rod mount hole<br>φ15 (0.59) x 23 (0.91) slot upper<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:585px;top:106px;font-weight:normal;font-size:9.07pt;\">");
write("<nobr><b>For torque rod mount hole<br>φ15 (0.59) x 23 (0.91) slot lower<br></b></nobr>");
write("</p>");
write("</div>");
write("<div id=\"bl1_1\" name=\"prt_bl\" class=\"drag\" from=\"301,593\" to=\"300,517\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_1\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">538 (21.2) c1</span>");
write("</div>");
write("<div id=\"bl1_2\" name=\"prt_bl\" class=\"drag\" from=\"326,592\" to=\"325,489\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_2\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">508 (20.0) c2</span>");
write("</div>");
write("<div id=\"bl1_3\" name=\"prt_bl\" class=\"drag\" from=\"542,634\" to=\"541,504\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_3\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">945 (37.2)</span>");
write("</div>");
write("<div id=\"bl1_4\" name=\"prt_bl\" class=\"drag\" from=\"573,642\" to=\"572,540\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_4\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">1033 (40.67) </span>");
write("</div>");
write("<div id=\"bl1_5\" name=\"prt_bl\" class=\"drag\" from=\"591,634\" to=\"590,536\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_5\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">987 (38.9)</span>");
write("</div>");
write("<div id=\"bl1_6\" name=\"prt_bl\" class=\"drag\" from=\"619,633\" to=\"618,533\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_6\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">890 (35.0)</span>");
write("</div>");
write("<div id=\"bl1_7\" name=\"prt_bl\" class=\"drag\" from=\"649,634\" to=\"648,538\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_7\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">958 (37.7)</span>");
write("</div>");
write("<div id=\"bl1_8\" name=\"prt_bl\" class=\"drag\" from=\"725,634\" to=\"724,532\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_8\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">638 (25.1)</span>");
write("</div>");
write("<div id=\"bl1_9\" name=\"prt_bl\" class=\"drag\" from=\"756,634\" to=\"755,536\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_9\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">940 (37.0)</span>");
write("</div>");
write("<div id=\"bl1_10\" name=\"prt_bl\" class=\"drag\" from=\"813,641\" to=\"812,516\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_10\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">1110 (43.70)</span>");
write("</div>");
write("<div id=\"bl1_11\" name=\"prt_bl\" class=\"drag\" from=\"873,634\" to=\"872,554\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_11\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">387 (15.2)</span>");
write("</div>");
write("<div id=\"bl1_12\" name=\"prt_bl\" class=\"drag\" from=\"1078,634\" to=\"1077,534\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_12\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">770 (30.3)</span>");
write("</div>");
write("<div id=\"bl1_13\" name=\"prt_bl\" class=\"drag\" from=\"1137,635\" to=\"1136,572\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_13\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">309 (12.2)</span>");
write("</div>");
write("<div id=\"bl1_14\" name=\"prt_bl\" class=\"drag\" from=\"1264,643\" to=\"1263,510\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_14\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">1298 (51.10)</span>");
write("</div>");
write("<div id=\"bl1_15\" name=\"prt_bl\" class=\"drag\" from=\"1293,635\" to=\"1292,517\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_15\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">800 (31.5)</span>");
write("</div>");
write("<div id=\"bl1_16\" name=\"prt_bl\" class=\"drag\" from=\"1376,643\" to=\"1375,540\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_16\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">1074 (42.28)</span>");
write("</div>");
write("<div id=\"bl1_17\" name=\"prt_bl\" class=\"drag\" from=\"1438,642\" to=\"1437,525\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_17\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">1011 (39.80)</span>");
write("</div>");
write("<div id=\"bl1_18\" name=\"prt_bl\" class=\"drag\" from=\"1661,635\" to=\"1660,559\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_18\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">232 (9.13)</span>");
write("</div>");
write("<div id=\"bl1_19\" name=\"prt_bl\" class=\"drag\" from=\"1603,635\" to=\"1602,550\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_19\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">900 (35.4)</span>");
write("</div>");
write("<div id=\"bl1_20\" name=\"prt_bl\" class=\"drag\" from=\"1560,635\" to=\"1559,537\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_20\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">878 (34.6)</span>");
write("</div>");
write("<div id=\"bl1_21\" name=\"prt_bl\" class=\"drag\" from=\"1492,564\" to=\"1491,489\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_21\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">145 (5.71)</span>");
write("</div>");
write("<div id=\"bl1_22\" name=\"prt_bl\" class=\"drag\" from=\"1493,726\" to=\"1492,642\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_22\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">155 (6.10)</span>");
write("</div>");
write("<div id=\"bl1_23\" name=\"prt_bl\" class=\"drag\" from=\"266,642\" to=\"265,514\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_23\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">1020 (40.16) a1</span>");
write("</div>");
write("<div id=\"bl1_24\" name=\"prt_bl\" class=\"drag\" from=\"364,741\" to=\"363,612\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_24\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">459 (18.1) d4</span>");
write("</div>");
write("<div id=\"bl1_25\" name=\"prt_bl\" class=\"drag\" from=\"339,742\" to=\"338,611\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_25\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">467 (18.4) d3</span>");
write("</div>");
write("<div id=\"bl1_26\" name=\"prt_bl\" class=\"drag\" from=\"315,742\" to=\"314,625\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_26\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">496 (19.5) d1</span>");
write("</div>");
write("<div id=\"bl1_27\" name=\"prt_bl\" class=\"drag\" from=\"290,742\" to=\"289,605\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_27\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">528 (20.8) d2</span>");
write("</div>");
write("<div id=\"bl1_28\" name=\"prt_bl\" class=\"drag\" from=\"350,592\" to=\"349,492\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_28\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">500 (19.7) c3</span>");
write("</div>");
write("<div id=\"bl1_29\" name=\"prt_bl\" class=\"drag\" from=\"375,592\" to=\"374,426\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp1_29\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:7.66pt;\">492 (19.4) e1,e2</span>");
write("</div>");
write("</div>");
}