with(document) {
write("<div id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:671px;\">");
write("<div id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:671px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/TL19EAQA20300000000DBAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:671px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765px;top:34px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:793px;top:45px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:851px;top:102px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:882px;top:199px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:14px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:624px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:597px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:635px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:874px;top:273px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:612px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:635px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:643px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18px;top:382px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ENGINE WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:426px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>LEFT ENGINE<br>COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}