with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:545px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:545px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E00J26220257121KDAD12.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:545px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:17px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>Fastener Locations<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77px;top:43px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>: Bolt, 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:43px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:43px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>: Bolt, 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:43px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:491px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:504px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:410px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:456px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:393px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:96px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:462px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:480px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m<br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:313px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m<br>(2.2 kgf·m,<br>16 lbf·ft)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}