with(document) {
write("<div id=\"group5\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1085px;\">");
write("<div id=\"rect5\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1085px;\">");
write("<img id=\"img5\" name=\"PrtImgId\" src=\"../img/TL19E9QJ54260400000EAAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1085px;border-color:#ffffff\">");
write("<p id=\"p5_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:926px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 6 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:195px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:30px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p5_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:91px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 1 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:85px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:241px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 4 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:559px;top:256px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:156px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:363px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:400px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p5_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:57px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p5_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:56px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286px;top:1021px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p5_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:400px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p5_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:51px;top:363px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:363px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:273px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ST<br></b></nobr>");
write("</p>");
write("<p id=\"p5_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:223px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:166px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p5_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123px;top:130px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p5_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:195px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:102px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p5_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:126px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 2 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:205px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 3 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:559px;top:313px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:298px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 5 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:313px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Gauge control module<br></b></nobr>");
write("</p>");
write("<p id=\"p5_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:328px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Shift lock solenoid (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:342px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Automatic dimming inside mirror<br></b></nobr>");
write("</p>");
write("<p id=\"p5_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:492px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Driver's MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:480px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:856px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Back−up lights<br></b></nobr>");
write("</p>");
write("<p id=\"p5_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:856px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:777px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Transmission range switch (R)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:777px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRY/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:970px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Yaw rate−lateral acceleration sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p5_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:400px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p5_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:559px;top:220px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:142px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:170px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:185px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Headlight leveling control unit (With HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:221px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p5_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:142px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left headlight leveling motor (Without HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:435px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p5_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:542px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:542px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816px;top:542px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:703px;top:542px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:608px;top:516px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BACK−UP LIGHT SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p5_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:585px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:602px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:613px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Driver's MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:585px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Back−up lights<br></b></nobr>");
write("</p>");
write("<p id=\"p5_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:866px;top:680px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:864px;top:495px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(M/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:823px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:835px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Driver's MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:877px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Automatic dimming inside mirror<br></b></nobr>");
write("</p>");
write("<p id=\"p5_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:877px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p5_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:877px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:42px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:657px;top:42px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p5_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:53px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:356px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Automatic lighting/rain sensor*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p5_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:667px;top:42px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>With automatic wiper<br></b></nobr>");
write("</p>");
write("<p id=\"p5_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:106px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>E−pretensioner unit (With ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:120px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LKAS unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:559px;top:120px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546px;top:106px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:170px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ACC unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:199px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power seat control unit (With DPMS)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:399px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Parking and back−up sensor control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:385px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Headlight washer/parking sensor switch<br></b></nobr>");
write("</p>");
write("<p id=\"p5_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:370px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Headlight washer switch<br></b></nobr>");
write("</p>");
write("<p id=\"p5_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:413px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LKAS camera<br></b></nobr>");
write("</p>");
write("<p id=\"p5_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:899px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:899px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Navigation unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:942px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:942px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>EPS control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:257px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p5_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:1050px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p5_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:156px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Millimeter wave radar (With ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:770px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p5_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:785px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT/GRN*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p5_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:792px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p5_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:956px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>VSA modulator−control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:667px;top:65px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>R20A3 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p5_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:667px;top:53px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K24Z3 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p5_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:657px;top:65px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p5_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:657px;top:53px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p5_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:65px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p5_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:656px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Navigation unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:656px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:634px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:635px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p5_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:635px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Automatic dimming inside mirror<br></b></nobr>");
write("</p>");
write("<p id=\"p5_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:293px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p5_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:559px;top:463px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:463px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power tailgate control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:585px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:856px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:188px;top:431px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>DRIVER'S <br>UNDER−DASH <br>FUSE/RELAY <br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p5_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:33px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>No. 3−1 (IG MAIN) <br>(50 A) FUSE <br>(UNDER−HOOD <br>FUSE/RELAY BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:431px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>DRIVER'S <br>UNDER−DASH <br>FUSE/RELAY <br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p5_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:31px;top:431px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>DRIVER'S <br>UNDER−DASH <br>FUSE/RELAY <br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p5_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:250px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>RELAY CIRCUIT BOARD <br>(Wiper motor relay circuit)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:735px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>REVERSE <br>RELAY <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:214px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>PASSENGER'S <br>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p5_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:429px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>PASSENGER'S <br>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p5_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:1043px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>RELAY CIRCUIT BOARD <br>(ACC relay circuit)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:986px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>Headlight leveling switch <br>(Without HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:1014px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>Right headlight leveling motor <br>(Without HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:286px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>PASSENGER'S <br>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}