with(document) {
write("<div id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:991px;\">");
write("<div id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:991px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/TL19EASA20300000000DBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:991px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:457px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:759px;top:489px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LEFT SIDE <br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:158px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RIGHT SIDE WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:15px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546px;top:14px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:854px;top:185px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:893px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:551px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>NAVIGATION UNIT (2)<br>(with navigation system)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:758px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FUEL HEATER<br>(4) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:551px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>12P JUNCTION<br>CONNECTOR (1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:552px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>LKAS CONTROL UNIT (3)<br>(with LKAS)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286px;top:746px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FUEL FILTER<br>WATER LEVEL<br>SWITCH (5) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:758px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>PRESUPPLY<br>FUEL PUMP (6)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}