with(document) {
write("<div id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\">");
write("<div id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/TL19EEB000000000000EBA321.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-93px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:454px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:461px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:408px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:492px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:419px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473px;top:419px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:481px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473px;top:481px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:408px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:492px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:494px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:494px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:437px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:519px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:417px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160px;top:417px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:519px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:551px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>386<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:565px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>68<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:237px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:330px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:373px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:545px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:651px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:280px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>289<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:237px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:330px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:373px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:280px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>211<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:524px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>402<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:524px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>438<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:373px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>134<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:373px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>159<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:503px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:596px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:617px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>496<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:237px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:330px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:237px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:330px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390px;top:280px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>330<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:280px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>356<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:437px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:446px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HAZARD <br>WARNING <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:544px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DASHLIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(In the gauge <br>control module) <br>(13−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:347px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A)*<sup>3</sup><br>FUSE <br>(4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:347px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 9 (15 A)*<sup>1</sup><br>FUSE <br>(3−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:544px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>MICU<br>(15−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:608px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S MICU <br>(15−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRAKE PEDAL <br>POSITION <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:571px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM <br>(10−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157px;top:348px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 7 (15 A)*<sup>2</sup><br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:585px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC RELAY (2−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:592px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (10−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 7 (15 A)*<sup>2</sup><br>FUSE <br>(6−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:455px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(Open: <br>Brake pedal released) <br>(Closed: <br>Brake pedal pressed)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:455px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(Open: <br>Brake pedal pressed) <br>(Closed: <br>Brake pedal released)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:348px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 12 (15 A)*<sup>1</sup><br>FUSE <br>(1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 12 (15 A)*<sup>1</sup><br>FUSE <br>(5−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:637px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>MICU<br>(17−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A)*<sup>3</sup><br>FUSE <br>(8−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 9 (15 A)*<sup>1</sup><br>FUSE <br>(7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:585px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:607px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:600px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TCM (12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:600px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:592px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:670px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>267<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:713px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S MICU <br>(17−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:690px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC RELAY (6−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:698px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (10−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:690px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:713px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:705px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TCM (12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:706px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:698px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55px;top:667px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(RHD model)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-51px;top:510px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-51px;top:457px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-51px;top:603px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-53px;top:648px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G901<br></b></nobr>");
write("</p>");
write("<p id=\"p3_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-39px;top:550px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-24px;top:277px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-24px;top:370px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:457px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:603px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:648px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p3_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:51px;top:523px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:51px;top:550px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:277px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:370px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-50px;top:413px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>530<br></b></nobr>");
write("</p>");
write("<p id=\"p3_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-50px;top:320px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>338<br></b></nobr>");
write("</p>");
write("<p id=\"p3_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:413px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>545<br></b></nobr>");
write("</p>");
write("<p id=\"p3_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:320px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>353<br></b></nobr>");
write("</p>");
write("<p id=\"p3_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-99px;top:648px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G901<br></b></nobr>");
write("</p>");
write("<p id=\"p3_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:6px;top:550px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:6px;top:523px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-8px;top:648px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G901<br></b></nobr>");
write("</p>");
write("<p id=\"p3_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-6px;top:510px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-5px;top:603px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-178px;top:560px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LICENSE  <br>PLATE <br>LIGHTS<br>(5 W x 2)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-42px;top:561px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>TAILLIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-133px;top:560px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT <br>TAILLIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-218px;top:560px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT<br>FRONT <br>POSITION <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-236px;top:387px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>MICU<br>(17−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-242px;top:294px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 27 (10 A)*<sup>2</sup><br>FUSE <br>(7−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-59px;top:387px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>MICU<br>(17−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:294px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 27 (10 A)*<sup>2</sup><br>FUSE <br>(7−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49px;top:560px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT<br>FRONT <br>POSITION <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:387px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S <br>MICU<br>(18−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:29px;top:294px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 2 (10 A)*<sup>3</sup><br>FUSE <br>(8−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-87px;top:561px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT <br>INNER <br>TAILLIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:560px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>INNER <br>TAILLIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-130px;top:516px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4*<sup>8</sup><br>1*<sup>9</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-38px;top:516px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4*<sup>8</sup><br>1*<sup>9</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-66px;top:492px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:492px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p3_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:86px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:86px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:72px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:79px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:79px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:72px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:79px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:86px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:72px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:93px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:93px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:93px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>With automatic lighting system<br></b></nobr>");
write("</p>");
write("<p id=\"p3_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:108px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:107px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:100px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:100px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:100px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Without automatic lighting system<br></b></nobr>");
write("</p>");
write("<p id=\"p3_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:108px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p3_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:115px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:115px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:115px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p3_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:383px;top:152px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[     ]<br></b></nobr>");
write("</p>");
write("<p id=\"p3_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:152px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:152px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p3_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-511px;top:294px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 27 (10 A)*<sup>2</sup><br>FUSE <br>(3−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-396px;top:560px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>FRONT <br>POSITION <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-422px;top:387px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S <br>MICU<br>(16−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-415px;top:294px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 2 (10 A)*<sup>3</sup><br>FUSE <br>(4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-441px;top:560px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>INNER <br>TAILLIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:122px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p3_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:121px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:122px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4−door<br></b></nobr>");
write("</p>");
write("<p id=\"p3_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:129px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:129px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:129px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5−door<br></b></nobr>");
write("</p>");
write("<p id=\"p3_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:136px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*10<br></b></nobr>");
write("</p>");
write("<p id=\"p3_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:136px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:136px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>With automatic lighting<br></b></nobr>");
write("</p>");
write("<p id=\"p3_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:143px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:143px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*11<br></b></nobr>");
write("</p>");
write("<p id=\"p3_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:143px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Without automatic lighting<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}