with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19EC0000000000000EBA136.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:671px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:151px;top:624px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:611px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ILL BULB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:611px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MAIN GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:624px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:671px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:880px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:624px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:671px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:611px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>K−LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:611px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B−CAN H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:671px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:624px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:611px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B−CAN L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:671px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:624px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142px;top:725px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>357<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:725px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>369<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:725px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>368<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506px;top:725px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>367<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:745px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(In the gauge <br>control module) <br>(12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:745px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DATA LINK <br>CONNECTOR <br>(11−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:749px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE <br>(12−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:36px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>36<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:24px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>Audio System (With navigation system)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:580px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ILL+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:151px;top:566px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612px;top:566px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600px;top:580px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:433px;top:580px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443px;top:566px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:345px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AM/FM ANTENNA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:407px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANT +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:245px;top:392px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AMPLIFIER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:566px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:566px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276px;top:512px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AM/FM ANTENNA SUBLEAD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:485px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AM/FM ANTENNA LEAD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:407px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RF MAIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:407px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANT +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:392px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB AMPLIFIER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:345px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FM ANTENNA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:407px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RF SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:566px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:407px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RF MAIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372px;top:566px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:407px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RF SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:566px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:580px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANT +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:587px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:580px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RF MAIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:587px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:580px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RF SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:587px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:580px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RF MAIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:587px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:580px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RF SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:361px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:361px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:272px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:272px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:252px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:252px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:385px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:385px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:591px;top:398px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:591px;top:405px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:618px;top:405px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:618px;top:398px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:325px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534px;top:361px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:385px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:398px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:591px;top:280px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[BLK]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556px;top:282px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:468px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624px;top:468px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:468px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:308px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>165<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:265px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:265px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:282px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:308px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>337<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:494px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>168<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:451px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:494px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>173<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:451px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:451px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:468px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532px;top:494px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>347<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:451px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142px;top:494px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>144<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:375px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:358px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:401px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>316<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:214px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT FRONT <br>DOOR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520px;top:282px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 15 (20 A) <br>FUSE <br>(4−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418px;top:468px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 15 (10 A) <br>FUSE <br>(4−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587px;top:468px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 18 (7.5 A) <br>FUSE <br>(4−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:125px;top:468px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A) <br>FUSE <br>(4−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:423px;top:282px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 15 (20 A) <br>FUSE <br>(8−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:468px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 15 (10 A) <br>FUSE <br>(8−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:125px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A) <br>FUSE <br>(8−B)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}