with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:911px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:911px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E55E34150200000LDAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:911px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:796px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SYNCHRO SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:401px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1ST GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:778px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>COUNTERSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791px;top:99px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BALL BEARING<br></b>Check for wear<br>and operation.<br>Note the direction<br>of installation.<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:457px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>2ND GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791px;top:594px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRICTION DAMPER<br></b>Check for wear <br>and damage.<br>Note the direction of<br>installation.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:249px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SYNCHRO SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:178px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1ST/2ND <br>SYNCHRO HUB<br></b>Note the direction of<br>installation.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:465px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>NEEDLE BEARING<br></b>Check for wear and <br>operation.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:490px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>NEEDLE BEARING<br></b>Check for wear and <br>operation.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:360px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>4TH GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:306px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>5TH GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791px;top:407px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>3RD GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:550px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>2ND GEAR<br>DISTANCE COLLAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:322px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SYNCHRO CONE*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:541px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1ST GEAR<br>DISTANCE COLLAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:729px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SYNCHRO CONE*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:728px;top:19px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SPECIAL BOLT<br></b>NOTE: Left-hand threads.<br></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:244px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6TH GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:210px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>35 mm SHIM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:363px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INNER RING*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:280px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SYNCHRO RING*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791px;top:692px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INNER RING*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:877px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>*: This Components of the triple cone synchro assembly.<br></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:760px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SYNCHRO RING*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:728px;top:48px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>119 N·m (12.1 kgf·m, 87.5 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:42px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REVERSE GEAR<br>(1ST/2ND SYNCHRO SLEEVE)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}