with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:911px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:911px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E00R311000K5352YDAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:911px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:170px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>WHEELHOUSE<br>UPPER MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:433px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>WHEELHOUSE<br>LOWER MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:425px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>WHEELHOUSE<br>UPPER INNER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:190px;top:880px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>WHEELHOUSE LOWER<br>MEMBER SUPPORT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575px;top:415px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD UPPER<br>SIDE MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642px;top:170px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:590px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:850px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830px;top:280px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(5)<br>L=10 (0.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:215px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:466px;top:388px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:796px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:485px;top:713px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:760px;top:485px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>(A) and (B):<br>Inside of the dashboard<br>upper side member.<br></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:392px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:541px;top:419px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:716px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:715px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:651px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445px;top:425px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DAMPER<br>HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:653px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:776px;top:627px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(C) area<br>RHD model Driver's side<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:703px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Front<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:882px;top:666px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DAMPER<br>HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:850px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>WHEELHOUSE<br>INNER PATCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:836px;top:882px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>WHEELHOUSE<br>UPPER INNER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:856px;top:149px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(1)<br>L=10 (0.4)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}