with(document) {
write("<div id=\"group15\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\">");
write("<div id=\"rect15\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img15\" name=\"PrtImgId\" src=\"../img/TL19EGPJ54230100000EAAD15.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p15_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:239px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:239px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p15_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:168px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p15_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:167px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:132px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p15_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:132px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:96px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:96px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p15_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:60px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:60px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p15_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:382px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p15_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:61px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Ignition key switch<br></b></nobr>");
write("</p>");
write("<p id=\"p15_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:97px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Yaw rate−lateral acceleration sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p15_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:240px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Console accessory power socket<br></b></nobr>");
write("</p>");
write("<p id=\"p15_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:254px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Console accessory power socket relay<br></b></nobr>");
write("</p>");
write("<p id=\"p15_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:168px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cigarette lighter<br></b></nobr>");
write("</p>");
write("<p id=\"p15_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:203px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p15_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:203px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:204px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Ashtray light<br></b></nobr>");
write("</p>");
write("<p id=\"p15_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28px;top:27px;font-weight:normal;font-size:9.14pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p15_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:789px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p15_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:725px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p15_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:918px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p15_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:918px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Front passenger's door wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p15_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:110px;top:916px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p15_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:725px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:789px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:789px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p15_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:789px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:740px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Front passenger's power window switch<br></b></nobr>");
write("</p>");
write("<p id=\"p15_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:789px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left power mirror<br></b></nobr>");
write("</p>");
write("<p id=\"p15_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:660px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:625px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p15_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:625px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:860px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G505<br></b></nobr>");
write("</p>");
write("<p id=\"p15_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:625px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Passenger's MICU (PG)<br></b></nobr>");
write("</p>");
write("<p id=\"p15_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:661px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Passenger's MICU (SG)<br></b></nobr>");
write("</p>");
write("<p id=\"p15_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:725px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Front passenger's door lock knob switch<br></b></nobr>");
write("</p>");
write("<p id=\"p15_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:725px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:660px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p15_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:725px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p15_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:475px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p15_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:896px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p15_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:110px;top:895px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p15_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:896px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Dashboard wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p15_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:475px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:475px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SRS unit<br></b></nobr>");
write("</p>");
write("<p id=\"p15_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:440px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SRS unit<br></b></nobr>");
write("</p>");
write("<p id=\"p15_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:575px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G504<br></b></nobr>");
write("</p>");
write("<p id=\"p15_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:439px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:439px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p15_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:132px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Park−pin switch (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p15_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:304px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Front passenger's seat heater switch<br></b></nobr>");
write("</p>");
write("<p id=\"p15_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:290px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Driver's seat heater switch<br></b></nobr>");
write("</p>");
write("<p id=\"p15_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:289px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p15_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:289px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:325px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Parking and back−up sensor control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p15_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:325px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:325px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p15_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:511px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Front passenger's airbag ON/OFF switch<br></b></nobr>");
write("</p>");
write("<p id=\"p15_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:510px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p15_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:510px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p15_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:613px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p15_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:649px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p15_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:268px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cargo area accessory power socket relay<br></b></nobr>");
write("</p>");
write("<p id=\"p15_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:754px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Front passenger's <br>door super locking actuator<br></b></nobr>");
write("</p>");
write("<p id=\"p15_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:570px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>PASSENGER'S <br>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}