with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E9PJ54200000000DEAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:639px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PARKING and BACK-UP SENSOR CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:721px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>STARTER CUT RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103px;top:701px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CIGARETTE LIGHTER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71px;top:748px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PGM-FI MAIN RELAY 2<br>(FUEL PUMP)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544px;top:1046px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DRIVER'S MICU<br>(Built into the driver's<br>under-dash fuse/relay box)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:1060px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DRIVER'S UNDER-DASH<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:675px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HEADLIGHT LEVERING CONTROL UNIT (With HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:565px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ACC UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:128px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONSOLE ACCESSORY POWER SOCKET RELAY<br></b>Wire colors: PNK, LT BLU, BLK,<br>and PUR<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:179px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SECURITY HORN RELAY<br></b>Wire colors: BRN, RED, GRY,<br>and RED<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:69px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DAYTIME RUNNING LIGHTS RELAY<br></b>Wire colors: PNK, WHT, WHT, GRY,<br>and WHT<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:121px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HEADLIGHT WASHER RELAY<br></b>Wire colors: GRN, WHT, ORN,<br>and WHT<br></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:178px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CARGO AREA ACCESSORY POWER SOCKET RELAY<br></b>Wire colors: BLU, LT BLU, BLK,<br>and PUR<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}