with(document) {
write("<div id=\"group15\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect15\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img15\" name=\"PrtImgId\" src=\"../img/TL19E20A20300000000EAAD15.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p15_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:94px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p15_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:777px;top:582px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>VSA MODULATOR- <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p15_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:129px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p15_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:161px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p15_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:192px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p15_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:346px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p15_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:382px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p15_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:391px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p15_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203px;top:515px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p15_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203px;top:550px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p15_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:574px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p15_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:604px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p15_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:384px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p15_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:404px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p15_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:422px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p15_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:56px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>U<br></b></nobr>");
write("</p>");
write("<p id=\"p15_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:56px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>W<br></b></nobr>");
write("</p>");
write("<p id=\"p15_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392px;top:55px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p15_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772px;top:114px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YAW RATE-LATERAL<br>ACCELERATION SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p15_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42px;top:1029px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>*5: With navigation system<br>*7: LHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p15_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:87px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>K1<br></b></nobr>");
write("</p>");
write("<p id=\"p15_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:124px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>K2<br></b></nobr>");
write("</p>");
write("<p id=\"p15_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:154px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>H2<br></b></nobr>");
write("</p>");
write("<p id=\"p15_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:185px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>H1<br></b></nobr>");
write("</p>");
write("<p id=\"p15_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:339px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p15_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:376px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p15_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:500px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A18<br></b></nobr>");
write("</p>");
write("<p id=\"p15_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203px;top:535px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A19<br></b></nobr>");
write("</p>");
write("<p id=\"p15_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203px;top:597px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E8<br></b></nobr>");
write("</p>");
write("<p id=\"p15_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:33px;top:39px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>DRIVER'S JUNCTION BOX 2<br></b></nobr>");
write("</p>");
write("<p id=\"p15_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203px;top:566px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E7<br></b></nobr>");
write("</p>");
write("<p id=\"p15_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:583px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p15_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:613px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p15_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:355px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p15_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:200px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p15_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:102px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p15_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:138px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p15_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:169px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p15_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:735px;top:623px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>K-LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p15_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:655px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p15_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739px;top:685px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p15_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:367px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>20P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p15_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:384px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p15_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785px;top:959px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>NAVIGATION UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p15_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:757px;top:154px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p15_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:185px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p15_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:735px;top:919px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p15_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:949px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p15_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:699px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p15_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:727px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p15_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:721px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>H29<br></b></nobr>");
write("</p>");
write("<p id=\"p15_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201px;top:690px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>H11<br></b></nobr>");
write("</p>");
write("<p id=\"p15_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201px;top:705px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p15_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201px;top:736px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p15_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185px;top:872px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p15_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:901px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p15_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:949px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p15_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:183px;top:978px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p15_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:905px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p15_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:986px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p15_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:925px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P <br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p15_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:32px;top:461px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PASSENGER'S UNDER-DASH<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p15_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:793px;top:711px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>EPS CONTROL<br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p15_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:392px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p15_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:591px;top:392px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p15_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:441px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p15_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:461px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p15_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:480px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p15_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:498px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p15_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:518px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p15_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:537px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p15_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:733px;top:746px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>K-LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p15_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737px;top:778px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p15_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737px;top:808px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p15_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:170px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p15_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737px;top:201px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p15_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:457px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P <br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p15_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:692px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p15_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:50px;top:21px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p15_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:870px;top:883px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p15_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:607px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p15_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:638px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p15_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:668px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p15_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:731px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p15_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755px;top:762px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p15_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755px;top:792px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p15_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:753px;top:902px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p15_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:753px;top:933px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}