with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:593px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:593px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E00J18573430201KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:593px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:205px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:164px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:20px;top:368px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:441px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:521px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:559px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:447px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:17px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>Fastener Locations<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:43px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>: Screw, 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:43px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>: Clip, 4<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}