with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1023px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E60J26273400000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:276px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SUNVISOR<br><a href=\"javascript:CtsProc('0','000000000000358','i000')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:796px;top:458px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HEADLINER<br><a href=\"javascript:CtsProc('0','000000000002936','i000')\"></b>Removal/Installation,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71px;top:746px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TRUNK REAR <br>TRIM PANEL<br><a href=\"javascript:CtsProc('0','000000000002939','i000')\"></b>Removal/Installation,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:643px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TRUNK LID<br>TRIM PANEL<br></b>Removal/<br><a href=\"javascript:CtsProc('0','000000000002940','i000')\"> Installation,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:232px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT DOOR OPENING SEAL<br><a href=\"javascript:CtsProc('0','000000000000389','iR01')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418px;top:104px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REAR DOOR OPENING SEAL<br><a href=\"javascript:CtsProc('0','000000000000389','iR02')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:710px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT DOOR SILL TRIM<br><a href=\"javascript:CtsProc('0','000000000000389','iR01')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:595px;top:797px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REAR DOOR SILL TRIM<br><a href=\"javascript:CtsProc('0','000000000000389','iR02')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:60px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REAR PILLAR TRIM<br><a href=\"javascript:CtsProc('0','000000000000388','iR03')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:146px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CENTER PILLAR UPPER TRIM<br><a href=\"javascript:CtsProc('0','000000000000388','iR02')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:190px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GRAB HANDLE<br><a href=\"javascript:CtsProc('0','000000000000357','i000')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:760px;top:320px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT PILLAR TRIM<br><a href=\"javascript:CtsProc('0','000000000000388','iR01')\"></b>Removal/Installation,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:753px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CENTER PILLAR LOWER TRIM<br><a href=\"javascript:CtsProc('0','000000000000388','iR02')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:430px;top:928px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REAR SHELF<br><a href=\"javascript:CtsProc('0','000000000002938','iR01')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473px;top:884px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SPARE TYRE LID<br><a href=\"javascript:CtsProc('0','000000000002939','i000')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547px;top:840px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REAR BULKHEAD COVER<br><a href=\"javascript:CtsProc('0','000000000002938','iR01')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TRUNK LID HINGE TRIM<br><a href=\"javascript:CtsProc('0','000000000002940','iR02')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:572px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT SIDE OUTER TRIM<br><a href=\"javascript:CtsProc('0','000000000000389','iR01')\"></b>Removal/Installation,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:777px;top:515px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CARPET<br><a href=\"javascript:CtsProc('0','000000000000356','i000')\"></b>Replacement, <br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676px;top:628px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>KICK PANEL<br><a href=\"javascript:CtsProc('0','000000000000389','iR01')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:661px;top:666px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REAR SIDE OUTER TRIM<br><a href=\"javascript:CtsProc('0','000000000000389','iR02')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:371px;top:972px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TRUNK SIDE TRIM PANEL<br><a href=\"javascript:CtsProc('0','000000000002939','i000')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:863px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TOOL BOX SPACER<br><a href=\"javascript:CtsProc('0','000000000002939','i000')\"></b>Removal/Installation,<br></a><br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}