with(document) {
write("<div id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\">");
write("<div id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1071px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/TL19E8SA20300000000DBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:704px;top:783px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECM/PCM A (□) (24)*<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390px;top:586px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>INPUT SHAFT<br>(MAINSHAFT)<br>SPEED SENSOR<br>(18) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:661px;top:586px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>TRANSMISSION<br>RANGE SWITCH<br>(20) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:783px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECM/PCM C (○) (22)*<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:783px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECM/PCM B (△) (23)*<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:380px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>23P CONNECTOR (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473px;top:380px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ELD (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:380px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX (B) (11)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:379px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>TEST<br>TACHOMETER<br>CONNECTOR<br>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:380px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX (C) (12)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:40px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>MAP SENSOR<br>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:40px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>THROTTLE BODY<br>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:585px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>MAF SENSOR/<br>IAT SENSOR<br>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:40px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CMP SENSOR A<br>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791px;top:40px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>EVAP CANISTER<br>PURGE VALVE (6)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:727px;top:202px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>10P JUNCTION <br>CONNECTOR (10) (M/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643px;top:39px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CMP SENSOR B<br>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:368px;top:39px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECT SENSOR 1<br>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517px;top:586px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>OUTPUT SHAFT<br>(COUNTERSHAFT)<br>SPEED SENSOR<br>(19) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:202px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>A/F SENSOR<br>(SENSOR 1)<br>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:586px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>10P CONNECTOR<br>(17) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:202px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>24P JUNCTION CONNECTOR (9)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:57px;top:202px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>3P CONNECTOR (7)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:796px;top:585px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CKP SENSOR <br>(21)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:990px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br>*: Connector with female terminals (single outline): view from terminal side<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}