with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:481px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:481px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E9AJ46166453984KDAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:481px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:17px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Fastener Locations<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77px;top:43px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>: Bolt, 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:43px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:43px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>: Bolt, 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:43px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:54px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>A<br>8 x 1.25 mm<br>22 N·m<br>(2.2 kgf·m,<br>16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319px;top:402px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>B<br>6 x 1.0 mm<br>9.8 N·m<br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:388px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:342px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}