with(document) {
write("<div id=\"group11\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1007px;\">");
write("<div id=\"rect11\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1007px;\">");
write("<img id=\"img11\" name=\"PrtImgId\" src=\"../img/TL19ED3A20300000000DBAD11.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1007px;border-color:#ffffff\">");
write("<p id=\"p11_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:457px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p11_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781px;top:368px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LEFT SIDE <br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p11_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:158px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RIGHT SIDE WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p11_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:928px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br>*: Connector with female terminals (single outline): view from terminal side<br></nobr>");
write("</p>");
write("<p id=\"p11_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:15px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546px;top:14px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p11_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:854px;top:185px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p11_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:560px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>NAVIGATION UNIT (2)<br>(with navigation system)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:581px;top:805px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>PRESUPPLY<br>FUEL PUMP (4)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:560px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>12P JUNCTION<br>CONNECTOR (1)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:805px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>LKAS CONTROL UNIT (3)<br>(with ACC)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}