with(document) {
write("<div id=\"group7\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:687px;\">");
write("<div id=\"rect7\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:687px;\">");
write("<img id=\"img7\" name=\"PrtImgId\" src=\"../img/TL19ED3A20300000000DBAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:687px;border-color:#ffffff\">");
write("<p id=\"p7_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:41px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DRIVER'S JUNCTION BOX 2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:639px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DRIVER'S UNDER-DASH<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p7_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:813px;top:157px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DRIVER'S JUNCTION<br>BOX 1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:655px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>RIGHT SIDE WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:31px;top:468px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>E-PRETENSIONER<br>SUBHARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:7px;top:339px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>LEFT ENGINE<br>COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:17px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DASHBOARD WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417px;top:43px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>RIGHT ENGINE COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:113px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:52px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:83px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p7_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:750px;top:109px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765px;top:139px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p7_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654px;top:264px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p7_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:264px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p7_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:162px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p7_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:842px;top:254px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p7_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795px;top:366px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p7_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:594px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p7_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600px;top:630px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p7_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:602px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p7_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:561px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p7_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:351px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}