with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:1900px; height:950px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:1900px;height:950px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19ED0000000000000EBAD22.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:1900px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1166px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1609px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:494px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:579px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:473px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT HEADLIGHT LEVELING MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418px;top:473px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT HEADLIGHT LEVELING MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:430px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:430px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:668px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AV<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:421px;top:668px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:668px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:245px;top:888px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:768px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257px;top:721px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:688px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT LEVELING CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:828px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:805px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:828px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:795px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:795px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:795px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:795px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:828px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:805px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:828px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:721px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:721px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:721px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:721px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SSR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SSF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SV<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:668px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:768px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SCS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473px;top:795px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:721px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:721px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:768px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162px;top:701px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:701px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119px;top:768px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:721px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:896px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[G251]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:773px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:755px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1021px;top:602px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT HEADLIGHT LEVELING MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:983px;top:697px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:780px;top:602px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT HEADLIGHT LEVELING MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:921px;top:697px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:859px;top:697px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:728px;top:668px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>0<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715px;top:695px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715px;top:721px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:728px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:926px;top:602px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:869px;top:686px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:931px;top:686px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:997px;top:602px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:993px;top:686px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1055px;top:686px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:637px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:776px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:792px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:888px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1043px;top:888px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643px;top:711px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643px;top:719px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(0.84 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624px;top:591px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:792px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:637px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:662px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>732 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:715px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1000 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:742px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>232 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:817px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:768px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2050 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1046px;top:697px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:987px;top:591px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:917px;top:591px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:591px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624px;top:808px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:719px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(0.56 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:711px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806px;top:715px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:857px;top:888px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G302<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:688px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>681 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:852px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:939px;top:494px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718px;top:494px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:555px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1387px;top:677px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1708px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TILT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1764px;top:701px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(0.84 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1764px;top:694px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1756px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1635px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1688px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1618px;top:650px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1645px;top:650px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1702px;top:650px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1756px;top:650px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1746px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1179px;top:808px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1619px;top:888px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1363px;top:728px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1604px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1277px;top:770px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1303px;top:770px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1361px;top:770px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1188px;top:770px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1498px;top:593px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1489px;top:577px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1211px;top:684px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HALL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1645px;top:677px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CLOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1591px;top:677px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>OPEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1587px;top:650px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1578px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1246px;top:770px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1166px;top:593px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUNROOF CONTROL UNIT/MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1569px;top:712px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1667px;top:712px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1569px;top:719px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(OPEN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1667px;top:719px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(CLOSE)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1622px;top:764px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1631px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1552px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUNROOF SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1745px;top:764px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1485px;top:735px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UART<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1498px;top:770px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1489px;top:808px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1622px;top:826px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1176px;top:888px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1509px;top:490px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1294px;top:808px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1347px;top:808px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1263px;top:808px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1236px;top:808px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1240px;top:835px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1271px;top:835px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1297px;top:835px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1355px;top:835px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1581px;top:574px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1612px;top:574px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1639px;top:574px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1696px;top:574px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1764px;top:547px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:442px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(With HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1106px;top:371px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(Without HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:695px;top:821px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708px;top:850px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:779px;top:876px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:605px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>78<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:562px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:562px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:579px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:605px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>265<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119px;top:826px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>394<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:164px;top:826px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>395<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:817px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>392<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:835px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>382<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1747px;top:574px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>149<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1772px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1764px;top:454px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1747px;top:481px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>330<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1772px;top:437px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1747px;top:786px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>382<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1490px;top:844px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>520<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1489px;top:516px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>110<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1515px;top:473px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1418px;top:473px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1412px;top:490px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1392px;top:516px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>291<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:919px;top:520px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>77<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:943px;top:477px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:943px;top:384px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:939px;top:401px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:917px;top:427px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>265<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:697px;top:520px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>89<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722px;top:477px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722px;top:384px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718px;top:401px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:696px;top:427px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>270<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:520px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>149<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:651px;top:477px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:651px;top:384px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:427px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>330<br></b></nobr>");
write("</p>");
write("<p id=\"p1_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:401px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A) <br>FUSE <br>(4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120px;top:579px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 2 (7.5 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:857px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HALL <br>IC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:857px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HALL <br>IC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:890px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT SUSPENSION <br>STROKE SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:890px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REAR SUSPENSION <br>STROKE SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:838px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DATA LINK <br>CONNECTOR <br>(11−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:509px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT <br>LEVELING <br>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409px;top:509px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT <br>LEVELING <br>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:842px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GAUGE CONTROL <br>MODULE <br>(12−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1005px;top:630px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT <br>LEVELING <br>MOTOR <br>DRIVE <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:884px;top:630px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT <br>LEVELING <br>MOTOR <br>DRIVE <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563px;top:793px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT <br>LEVELING SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:610px;top:856px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(In the gauge <br>cobtrol module) <br>(12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:906px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 2 (7.5 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:684px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1365px;top:647px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>OPEN <br>RELAY <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1414px;top:647px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CLOSE <br>RELAY <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1733px;top:806px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(In the gauge <br>control module) <br>(12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1472px;top:854px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DOOR MULTIPLEX <br>CONTROL UNIT <br>(POWER WINDOW <br>MASTER SWITCH) <br>(24−C) (25−B) <br>(26−B) (27−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1474px;top:490px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 20 (20 A) <br>FUSE <br>(3−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1731px;top:548px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A) <br>FUSE <br>(4−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1272px;top:860px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUNROOF SWITCH <br>(24−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1596px;top:550px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUNROOF CONTROL SWITCH <br>(24−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:579px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 2 (7.5 A) <br>FUSE <br>(6−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1731px;top:455px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A) <br>FUSE <br>(8−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1376px;top:490px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 20 (20 A) <br>FUSE <br>(7−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:906px;top:402px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 2 (7.5 A) <br>FUSE <br>(6−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:684px;top:402px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A) <br>FUSE <br>(6−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613px;top:402px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A) <br>FUSE <br>(6−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1839px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1661px;top:77px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1661px;top:84px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1648px;top:77px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1648px;top:70px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1667px;top:77px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:23px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>Wipers/Washers, Headlight Leveling System, Sunroof<br></b></nobr>");
write("</p>");
write("<p id=\"p1_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1667px;top:84px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1704px;top:116px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CAN line<br></b></nobr>");
write("</p>");
write("<p id=\"p1_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1698px;top:116px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1661px;top:107px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1646px;top:107px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[     ]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1667px;top:107px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1661px;top:70px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1667px;top:70px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1648px;top:84px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1704px;top:125px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Other communication line<br></b></nobr>");
write("</p>");
write("<p id=\"p1_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1698px;top:125px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:265px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[1]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:265px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[3]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:265px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[4]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:349px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:278px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:409px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G302<br></b></nobr>");
write("</p>");
write("<p id=\"p1_274\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:369px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_275\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:287px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_276\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_277\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_278\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_279\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:848px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_280\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:914px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_281\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:941px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_282\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:981px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_283\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1077px;top:323px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WIPER/WASHER SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_284\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812px;top:259px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_285\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:829px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_286\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:879px;top:259px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MIST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_287\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:846px;top:239px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_288\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_289\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:930px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_290\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:970px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_291\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:904px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_292\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:836px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_293\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_294\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_295\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:349px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WIPER MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_296\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:417px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[G201]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_297\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1156px;top:65px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_298\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_299\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:273px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_300\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_301\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:253px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[LT BLU]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_302\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1210px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_303\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1282px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_304\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1318px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_305\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1384px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_306\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1411px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_307\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1451px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_308\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1543px;top:323px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WIPER/WASHER SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_309\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1282px;top:259px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_310\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1299px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_311\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1349px;top:259px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MIST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_312\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1316px;top:239px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_313\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1332px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_314\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1400px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_315\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1440px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_316\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1374px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_317\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1306px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_318\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1272px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_319\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1200px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_320\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1622px;top:65px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_321\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1661px;top:99px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_322\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1648px;top:99px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_323\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1648px;top:92px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_324\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1667px;top:92px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_325\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1661px;top:91px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_326\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1667px;top:99px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_327\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:121px;top:210px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>56<br></b></nobr>");
write("</p>");
write("<p id=\"p1_328\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152px;top:210px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>57<br></b></nobr>");
write("</p>");
write("<p id=\"p1_329\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:210px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>420<br></b></nobr>");
write("</p>");
write("<p id=\"p1_330\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119px;top:112px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>245<br></b></nobr>");
write("</p>");
write("<p id=\"p1_331\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:151px;top:112px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>246<br></b></nobr>");
write("</p>");
write("<p id=\"p1_332\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:112px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>474<br></b></nobr>");
write("</p>");
write("<p id=\"p1_333\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:163px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_334\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:65px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_335\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:65px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_336\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:163px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_337\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:210px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>182<br></b></nobr>");
write("</p>");
write("<p id=\"p1_338\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_339\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:65px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_340\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:163px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_341\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:112px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>364<br></b></nobr>");
write("</p>");
write("<p id=\"p1_342\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329px;top:409px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G651<br></b></nobr>");
write("</p>");
write("<p id=\"p1_343\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:108px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>412<br></b></nobr>");
write("</p>");
write("<p id=\"p1_344\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:802px;top:108px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>413<br></b></nobr>");
write("</p>");
write("<p id=\"p1_345\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838px;top:108px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>414<br></b></nobr>");
write("</p>");
write("<p id=\"p1_346\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:904px;top:108px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>415<br></b></nobr>");
write("</p>");
write("<p id=\"p1_347\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:931px;top:108px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>416<br></b></nobr>");
write("</p>");
write("<p id=\"p1_348\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:971px;top:117px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>419<br></b></nobr>");
write("</p>");
write("<p id=\"p1_349\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1201px;top:108px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>466<br></b></nobr>");
write("</p>");
write("<p id=\"p1_350\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1272px;top:108px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>467<br></b></nobr>");
write("</p>");
write("<p id=\"p1_351\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1308px;top:108px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>468<br></b></nobr>");
write("</p>");
write("<p id=\"p1_352\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1374px;top:108px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>469<br></b></nobr>");
write("</p>");
write("<p id=\"p1_353\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1401px;top:108px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>470<br></b></nobr>");
write("</p>");
write("<p id=\"p1_354\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1441px;top:117px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>473<br></b></nobr>");
write("</p>");
write("<p id=\"p1_355\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:257px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_356\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:257px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_357\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:257px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_358\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:356px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[2]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_359\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:325px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_360\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:617px;top:365px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G651<br></b></nobr>");
write("</p>");
write("<p id=\"p1_361\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_362\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:273px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_363\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_364\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:272px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_365\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_366\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:440px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G901<br></b></nobr>");
write("</p>");
write("<p id=\"p1_367\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_368\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_369\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_370\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:405px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_371\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:371px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_372\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:272px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_373\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:433px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_374\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:433px;top:298px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_375\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:163px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_376\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:65px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_377\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:163px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_378\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:65px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_379\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646px;top:163px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_380\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646px;top:65px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_381\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1467px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_382\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1551px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_383\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1512px;top:260px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_384\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1480px;top:247px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_385\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1497px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_386\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1480px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WIP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_387\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1453px;top:285px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_388\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1453px;top:278px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_389\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1512px;top:253px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_390\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1591px;top:285px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_391\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1591px;top:278px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_392\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1533px;top:260px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_393\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1533px;top:253px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_394\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1565px;top:247px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_395\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1565px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WIP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_396\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1581px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_397\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1481px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_398\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1560px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_399\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:997px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_400\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1081px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_401\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1042px;top:260px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_402\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1010px;top:247px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_403\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1027px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_404\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1010px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WIP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_405\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:983px;top:285px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_406\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:983px;top:278px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_407\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1042px;top:253px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_408\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1121px;top:285px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_409\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1121px;top:278px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_410\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1063px;top:260px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_411\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1063px;top:253px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_412\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1095px;top:247px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_413\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1095px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WIP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_414\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1111px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_415\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1011px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_416\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1090px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_417\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1002px;top:108px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>417<br></b></nobr>");
write("</p>");
write("<p id=\"p1_418\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1082px;top:108px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>418<br></b></nobr>");
write("</p>");
write("<p id=\"p1_419\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:210px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>178<br></b></nobr>");
write("</p>");
write("<p id=\"p1_420\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:113px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>360<br></b></nobr>");
write("</p>");
write("<p id=\"p1_421\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:210px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>456<br></b></nobr>");
write("</p>");
write("<p id=\"p1_422\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:112px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>514<br></b></nobr>");
write("</p>");
write("<p id=\"p1_423\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:210px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>181<br></b></nobr>");
write("</p>");
write("<p id=\"p1_424\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:112px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>363<br></b></nobr>");
write("</p>");
write("<p id=\"p1_425\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1472px;top:108px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>471<br></b></nobr>");
write("</p>");
write("<p id=\"p1_426\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1552px;top:108px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>472<br></b></nobr>");
write("</p>");
write("<p id=\"p1_427\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613px;top:253px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[LT BLU]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_428\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749px;top:265px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INTERMITTENT <br>DWELL TIME <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_429\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:940px;top:283px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WASHER <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_430\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:179px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WIPER HIGH/LOW <br>RELAY CIRCUIT <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_431\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:184px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>MICU<br>(16−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_432\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:886px;top:85px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S MICU<br>(14−C, D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_433\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:292px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WINDSHIELD <br>WASHER <br>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_434\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:176px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WINDSHIELD <br>WASHER MOTOR <br>RELAY CIRCUIT <br>(4−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_435\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1219px;top:265px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INTERMITTENT <br>DWELL TIME <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_436\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1410px;top:283px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WASHER <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_437\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1360px;top:85px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S MICU<br>(16−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_438\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:82px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WIPER HIGH/LOW <br>RELAY CIRCUIT <br>(6−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_439\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:86px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>MICU<br>(16−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_440\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:79px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WINDSHIELD <br>WASHER MOTOR <br>RELAY CIRCUIT <br>(8−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_441\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:285px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WINDSHIELD/ <br>REAR WINDOW <br>WASHER <br>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_442\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496px;top:394px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REAR WINDOW <br>WIPER MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_443\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:425px;top:176px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REAR WINDOW <br>WIPER MOTOR <br>RELAY <br>(4−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_444\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:176px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REAR WINDOW <br>WASHER RELAY <br>CIRCUIT <br>(4−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_445\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:184px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S <br>MICU <br>(15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_446\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:425px;top:79px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REAR WINDOW <br>WIPER MOTOR <br>RELAY <br>(8−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_447\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:86px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S <br>MICU <br>(17−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_448\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:79px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REAR WINDOW <br>WASHER RELAY <br>CIRCUIT <br>(8−D)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}