with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:799px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:799px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E4AE34151400000MFAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:799px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>20 mm THRUST NEEDLE BEARING<br></b>Check for wear and operation.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:327px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REVERSE <br>SLEEVE SET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:431px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>20 mm THRUST <br>NEEDLE BEARING<br></b>Check for wear <br>and operation.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:580px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REVERSE  DRIVE GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:644px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>20 mm THRUST  WASHER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:705px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>33 mm SPRING WASHER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:768px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REVERSE IDLER GEAR SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:29px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>20 mm THRUST  WASHER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:66px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REVERSE <br>SLEEVE SET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:273px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SYNCHRO<br>SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:476px;top:311px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REVERSE <br>SYNCHRO<br>RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:362px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>NEEDLE<br>BEARING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:413px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>20 mm THRUST  WASHER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:462px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>NEEDLE BEARING<br></b>Check for wear and operation.<br></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:512px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>20 mm THRUST NEEDLE BEARING<br></b>Check for wear and operation.<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}