with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:353px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:353px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E9PJ54300065801FHAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:353px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:89px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:121px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>INT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:153px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>LO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:186px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>HI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:25px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Terminal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49px;top:57px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:218px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Mist ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:250px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Washer ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:274px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Intermittent dwell<br>timer turned<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:41px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:41px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:41px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:41px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:41px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443px;top:41px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:62px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>[4]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237px;top:62px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>[2]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:63px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>[1]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:62px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>[3]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:61px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>[8]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:61px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>[5]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:31px;top:322px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>[  ]: KQ model<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}