with(document) {
write("<div id=\"group7\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\">");
write("<div id=\"rect7\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img7\" name=\"PrtImgId\" src=\"../img/TL19EC1J54260400000EAAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p7_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:371px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 21 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:414px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 22 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:558px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Driver's MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p7_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:546px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:32px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p7_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:258px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:328px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 20 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:343px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:386px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:343px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Sunroof control unit/motor<br></b></nobr>");
write("</p>");
write("<p id=\"p7_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:671px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 23 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:799px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 24 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:909px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p7_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:106px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 8 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:87px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p7_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:165px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:165px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Starter solenoid<br></b></nobr>");
write("</p>");
write("<p id=\"p7_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71px;top:223px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p7_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:709px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p7_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:242px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 14 (Not used)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:122px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:615px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear power window switch<br></b></nobr>");
write("</p>");
write("<p id=\"p7_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:285px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 19 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451px;top:300px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p7_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:300px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power seat control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p7_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:386px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power seat control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p7_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:429px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:429px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear power window switch<br></b></nobr>");
write("</p>");
write("<p id=\"p7_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542px;top:453px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(With all power windows AUTO UP/AUTO DOWN function)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:615px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:646px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Without all power windows AUTO UP/AUTO DOWN function)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:815px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:615px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:429px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:386px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:300px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:122px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:122px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ECM (STS)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:32px;top:167px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>No. 3−4 (DR F/B) (60 A) <br>FUSE <br>(UNDER−HOOD <br>FUSE/RELAY BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:741px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>CIGARETTE <br>LIGHTER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p7_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:55px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>IGNITION <br>SWITCH (ST)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273px;top:516px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>LEFT REAR <br>POWER WINDOW <br>RELAY CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:815px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Door multiplex control unit <br>(Power window master switch)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}