with(document) {
write("<div id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\">");
write("<div id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/TL19EEB000000000000EBA239.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-124px;top:562px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ILL BULB<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-179px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY*<sup>5</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-179px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY*<sup>5</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-347px;top:691px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S <br>MICU <br>(16−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-248px;top:691px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HANDS FREE TELEPHONE <br>CONTROL UNIT <br>(41−C, D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-347px;top:784px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S <br>MICU <br>(18−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:617px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:617px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:617px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:617px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:178px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:125px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:151px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY*<sup>5</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:618px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:63px;top:618px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:26px;top:618px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:667px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANC<br>FR+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:667px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANC<br>FR−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:164px;top:667px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANC<br>RR+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:667px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANC<br>RR−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222px;top:667px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SH ANC<br>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86px;top:667px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:63px;top:667px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SWD<br>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:23px;top:667px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANC<br>CHK2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:713px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:781px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>403<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:713px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:738px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:774px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>449<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:63px;top:700px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NEP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INTR<br>LT−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:791px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM<br>(10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:684px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACTIVE NOISE CANCELLATION UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:12px;top:738px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:20px;top:714px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:10px;top:791px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:10px;top:701px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANC F<br>MIC 8 V<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SH ANCM<br>F GND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:785px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACTIVE NOISE<br>CANCELLATION<br>FRONT MICROPHONE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:738px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:155px;top:712px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:767px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:232px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANC R<br>MIC 8 V<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SH ANCM<br>R GND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237px;top:785px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACTIVE NOISE<br>CANCELLATION<br>REAR MICROPHONE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:239px;top:738px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:712px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:767px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:722px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK*<sup>5</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274px;top:722px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK*<sup>5</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274px;top:756px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK*<sup>5</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:712px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:712px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:767px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276px;top:847px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(4−door)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:576px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:554px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANC<br>CHK2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:756px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:722px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:179px;top:756px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK*<sup>5</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:188px;top:767px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:792px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S<br>MICU<br>(15−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:822px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:772px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>507<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:792px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S<br>MICU<br>(17−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:822px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-556px;top:24px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>Audio System (Premium audio system, Without navigation system)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-77px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-66px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-75px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:417px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SH FR−FL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:417px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PRE−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PRE+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:417px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:417px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PRE+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PRE−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:417px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PRE−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PRE+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A23<br></b></nobr>");
write("</p>");
write("<p id=\"p2_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:467px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:480px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A22<br></b></nobr>");
write("</p>");
write("<p id=\"p2_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:438px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:438px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B24<br></b></nobr>");
write("</p>");
write("<p id=\"p2_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495px;top:438px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:438px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A18<br></b></nobr>");
write("</p>");
write("<p id=\"p2_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A19<br></b></nobr>");
write("</p>");
write("<p id=\"p2_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A21<br></b></nobr>");
write("</p>");
write("<p id=\"p2_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PRE+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PRE−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SH FR−FL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522px;top:438px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:409px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>STEREO AMPLIFIER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SAT R<br></b></nobr>");
write("</p>");
write("<p id=\"p2_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583px;top:401px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SAT R<br></b></nobr>");
write("</p>");
write("<p id=\"p2_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556px;top:401px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SAT L<br></b></nobr>");
write("</p>");
write("<p id=\"p2_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:401px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SAT L<br></b></nobr>");
write("</p>");
write("<p id=\"p2_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:401px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CTR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:401px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:401px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CTR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:300px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:300px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A17<br></b></nobr>");
write("</p>");
write("<p id=\"p2_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:300px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:300px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:300px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:300px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:321px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:321px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:438px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555px;top:511px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p2_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582px;top:511px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p2_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:438px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:356px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:356px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:356px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:356px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:208px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:208px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:188px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:188px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55px;top:401px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:401px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:321px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:188px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:188px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:208px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:208px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:239px;top:188px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:188px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:321px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:401px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:401px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:188px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:188px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:356px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:356px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:321px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:208px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:208px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:208px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:208px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:300px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:300px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:300px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:300px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:269px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUBWOOFER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:272px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:272px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUBW<br></b></nobr>");
write("</p>");
write("<p id=\"p2_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUBW<br></b></nobr>");
write("</p>");
write("<p id=\"p2_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:356px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:356px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273px;top:356px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:356px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:356px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:356px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B18<br></b></nobr>");
write("</p>");
write("<p id=\"p2_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:438px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:438px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:480px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:480px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:438px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:417px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SH ELS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DATA−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DATA+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296px;top:417px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ELS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DATA+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DATA−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ELS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SH ELS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ELS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:494px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:494px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:467px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:486px;top:494px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:485px;top:467px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:417px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ELS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[BLK]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:216px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[BLK]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628px;top:480px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>K−LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:351px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY*<sup>5</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:351px;top:502px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY*<sup>5</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY*<sup>5</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:502px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY*<sup>5</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:4px;top:308px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>181<br></b></nobr>");
write("</p>");
write("<p id=\"p2_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-75px;top:405px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>185<br></b></nobr>");
write("</p>");
write("<p id=\"p2_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:454px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>414<br></b></nobr>");
write("</p>");
write("<p id=\"p2_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:265px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:172px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:4px;top:215px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>361<br></b></nobr>");
write("</p>");
write("<p id=\"p2_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-49px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-49px;top:269px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-75px;top:312px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>384<br></b></nobr>");
write("</p>");
write("<p id=\"p2_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-463px;top:238px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 16 (7.5 A)*<sup>2</sup><br>FUSE <br>(2−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:255px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT <br>CENTER <br>SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:255px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT REAR <br>SATELLITE <br>SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:255px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT REAR <br>SATELLITE <br>SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:150px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT FRONT <br>DOOR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:150px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT FRONT <br>DOOR TWEETER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:150px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT FRONT <br>DOOR TWEETER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:150px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT FRONT <br>DOOR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_274\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274px;top:255px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT REAR <br>DOOR <br>SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_275\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:255px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT REAR <br>DOOR <br>SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_276\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:418px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DATA LINK <br>CONNECTOR <br>(11−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_277\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-361px;top:237px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A)*<sup>3</sup><br>FUSE <br>(4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_278\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-174px;top:282px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 15 (10 A)*<sup>1</sup> <br>FUSE <br>(4−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_279\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-94px;top:379px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 18 (7.5 A)*<sup>2</sup><br>FUSE <br>(4−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_280\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-14px;top:282px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 15 (20 A)*<sup>3</sup><br>FUSE <br>(4−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_281\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-463px;top:145px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 16 (7.5 A)*<sup>2</sup><br>FUSE <br>(6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_282\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-361px;top:144px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A)*<sup>3</sup><br>FUSE <br>(8−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_283\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-173px;top:189px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 15 (10 A)*<sup>1</sup><br>FUSE <br>(8−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_284\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-13px;top:189px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 15 (20 A)*<sup>3</sup> <br>FUSE <br>(8−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_285\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-95px;top:287px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 18 (7.5 A)*<sup>2</sup><br>FUSE <br>(8−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_286\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-439px;top:470px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CLIMATE <br>CONTROL UNIT <br>(37−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_287\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WOOFER <br>SPEAKER BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_288\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:300px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_289\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:300px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_290\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_291\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_292\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:269px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUBWOOFER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_293\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_294\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUBW<br></b></nobr>");
write("</p>");
write("<p id=\"p2_295\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_296\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUBW<br></b></nobr>");
write("</p>");
write("<p id=\"p2_297\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_298\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:421px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_299\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:462px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_300\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13px;top:439px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_301\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SWD<br>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_302\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:506px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_303\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A17<br></b></nobr>");
write("</p>");
write("<p id=\"p2_304\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:438px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_305\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:438px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_306\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:437px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_307\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203px;top:438px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_308\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:417px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANC<br>FR+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_309\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136px;top:417px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANC<br>FR−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_310\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:164px;top:417px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANC<br>RR+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_311\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:417px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANC<br>RR−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_312\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:418px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SWD<br>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_313\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555px;top:342px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[PNK]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_314\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:581px;top:342px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[BRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_315\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_316\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_317\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:425px;top:232px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(4−door)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_318\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:232px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(5−door)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}