with(document) {
write("<div id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\">");
write("<div id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/TL19ED0000000000000EBA203.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:572px;top:489px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-557px;top:23px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>Driver's Under−dash Fuse/Relay Box (LHD model)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-133px;top:480px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S MICU (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-133px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUNROOF CONTROL UNIT/MOTOR (22−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-133px;top:232px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>STARTER SOLENOID (9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-133px;top:515px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT REAR POWER WINDOW SWITCH (26−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-133px;top:307px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>POWER SEAT CONTROL UNIT (30−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-133px;top:360px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>POWER SEAT CONTROL UNIT (30−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-133px;top:391px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT REAR POWER WINDOW SWITCH (24−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-135px;top:411px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(With all power windows AUTO UP/AUTO DOWN function)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-144px;top:535px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(Without all power windows AUTO UP/AUTO DOWN function)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S MICU (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:615px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:586px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:657px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:349px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:356px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S MICU (14−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:289px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S DOOR LOCK ACTUATOR (15−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:697px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:195px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 25 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:440px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S MICU (14−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:289px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:311px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:311px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT REAR DOOR LOCK ACTUATOR (15−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FUEL FILL LOCK ACTUATOR (15−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S DOOR LOCK ACTUATOR (15−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:418px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FUEL FILL LOCK ACTUATOR (15−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:493px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT REAR DOOR LOCK ACTUATOR (15−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:493px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S MICU (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:522px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:418px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:311px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:585px;top:130px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555px;top:103px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556px;top:516px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555px;top:751px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555px;top:582px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>49<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:290px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>116<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:334px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>118<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:356px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>119<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:396px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>120<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:440px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>122<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:494px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>123<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:529px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>124<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:587px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>125<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>126<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:312px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>117<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:418px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>121<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:195px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544px;top:84px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575px;top:556px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:576px;top:724px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-133px;top:205px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (STS) (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:489px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 9 (15 A) <br>FUSE <br>(1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-524px;top:259px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 3−4 <br>(DR F/B)(60 A) <br>FUSE (1−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-346px;top:607px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CIGARETTE <br>LIGHTER RELAY <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-382px;top:454px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT REAR <br>POWER WINDOW <br>RELAY CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:562px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TAILGATE RELEASE <br>ACTUATOR RELAY CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:367px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>POWER DOOR LOCK <br>RELAY CIRCUIT (DR UNLOCK)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:260px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>POWER DOOR LOCK <br>RELAY CIRCUIT (LOCK)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:464px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>POWER DOOR LOCK <br>RELAY CIRCUIT (UNLOCK)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:77px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 3−5 (DR LT MAIN) <br>(40 A) <br>FUSE (1−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:556px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 15 (10 A) <br>FUSE <br>(1−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:724px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 16 (7.5 A) <br>FUSE <br>(1−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:587px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TAILGATE RELEASE ACTUATOR <br>(Without power tailgate) (15−B)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}