with(document) {
write("<div id=\"group7\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:687px;\">");
write("<div id=\"rect7\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:687px;\">");
write("<img id=\"img7\" name=\"PrtImgId\" src=\"../img/TL19E6BA20300000000DBAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:687px;border-color:#ffffff\">");
write("<p id=\"p7_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:69px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653px;top:64px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p7_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:70px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:91px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p7_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:86px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:280px;top:589px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p7_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:626px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p7_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:632px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p7_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:620px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p7_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:618px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p7_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:614px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p7_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624px;top:615px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p7_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:857px;top:367px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p7_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:840px;top:418px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p7_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:529px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p7_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:602px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p7_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:826px;top:472px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>LEFT ENGINE<br>COMPARTMENT<br>SUBHARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:581px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>LEFT ENGINE<br>COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830px;top:269px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>CABLE REEL<br>SUBHARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:48px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DASHBOARD WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:642px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>LEFT SIDE WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:518px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DRIVER'S <br>JUNCTION BOX 1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:447px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DRIVER'S <br>JUNCTION BOX 2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:17px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DRIVER'S UNDER-DASH<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p7_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:654px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>M/T<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}