with(document) {
write("<div id=\"group11\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect11\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img11\" name=\"PrtImgId\" src=\"../img/TL19E6PA20300000000EAAD11.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p11_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:817px;top:85px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ETCS <br>CONTROL<br>RELAY <br></b></nobr>");
write("</p>");
write("<p id=\"p11_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:774px;top:38px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773px;top:144px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773px;top:251px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773px;top:364px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:751px;top:555px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A/C COMPRESSOR<br>CLUTCH RELAY <br></b></nobr>");
write("</p>");
write("<p id=\"p11_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:918px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:893px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:832px;top:918px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:608px;top:981px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ELD<br></b></nobr>");
write("</p>");
write("<p id=\"p11_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:836px;top:1063px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p11_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:21px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p11_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:842px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:867px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:423px;top:831px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:671px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p11_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:696px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p11_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:725px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p11_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:744px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B9<br></b></nobr>");
write("</p>");
write("<p id=\"p11_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:948px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:970px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p11_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:1002px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:992px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p11_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:1065px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p11_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:395px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:514px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:585px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>C2<br></b></nobr>");
write("</p>");
write("<p id=\"p11_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:604px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>C3<br></b></nobr>");
write("</p>");
write("<p id=\"p11_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:495px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p11_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:566px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>C6<br></b></nobr>");
write("</p>");
write("<p id=\"p11_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:548px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>C5<br></b></nobr>");
write("</p>");
write("<p id=\"p11_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:477px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:78px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>C1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:101px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>IG1ETCS<br></b></nobr>");
write("</p>");
write("<p id=\"p11_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:49px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>23P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p11_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:29px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p11_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:377px;top:30px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p11_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:162px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Z<br></b></nobr>");
write("</p>");
write("<p id=\"p11_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:922px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A24<br></b></nobr>");
write("</p>");
write("<p id=\"p11_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:938px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ELD<br></b></nobr>");
write("</p>");
write("<p id=\"p11_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:780px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p11_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:376px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:376px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p11_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:393px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>FANH<br></b></nobr>");
write("</p>");
write("<p id=\"p11_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:338px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p11_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:355px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>FANL<br></b></nobr>");
write("</p>");
write("<p id=\"p11_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:300px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p11_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:317px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p11_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:262px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A22<br></b></nobr>");
write("</p>");
write("<p id=\"p11_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:279px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SUBRLY<br></b></nobr>");
write("</p>");
write("<p id=\"p11_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:224px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A7<br></b></nobr>");
write("</p>");
write("<p id=\"p11_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:241px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>MRLY<br></b></nobr>");
write("</p>");
write("<p id=\"p11_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:585px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A42<br></b></nobr>");
write("</p>");
write("<p id=\"p11_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:601px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BKSW<br></b></nobr>");
write("</p>");
write("<p id=\"p11_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:196px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A21<br></b></nobr>");
write("</p>");
write("<p id=\"p11_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:212px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ETCSRLY<br></b></nobr>");
write("</p>");
write("<p id=\"p11_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498px;top:772px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p11_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:858px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p11_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329px;top:1067px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AG<br></b></nobr>");
write("</p>");
write("<p id=\"p11_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369px;top:1068px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AH<br></b></nobr>");
write("</p>");
write("<p id=\"p11_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296px;top:1067px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AF<br></b></nobr>");
write("</p>");
write("<p id=\"p11_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:1023px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AI<br></b></nobr>");
write("</p>");
write("<p id=\"p11_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:163px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AD<br></b></nobr>");
write("</p>");
write("<p id=\"p11_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:415px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PGM-FI<br>SUBRELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p11_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:295px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PGM-FI<br>MAIN <br>RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:817px;top:194px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>IGNITION<br>COIL <br>RELAY <br></b></nobr>");
write("</p>");
write("<p id=\"p11_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:817px;top:789px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A/C<br>CONDENSER<br>FAN RELAY<br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816px;top:696px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>FAN <br>CONTROL <br>RELAY<br>CIRCUIT <br></b></nobr>");
write("</p>");
write("<p id=\"p11_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816px;top:610px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RADIATOR<br>FAN <br>RELAY <br></b></nobr>");
write("</p>");
write("<p id=\"p11_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:642px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AA<br></b></nobr>");
write("</p>");
write("<p id=\"p11_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:209px;top:430px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p11_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:431px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p11_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:478px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:453px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p11_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:78px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p11_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277px;top:74px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p11_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:50px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p11_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:107px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:87px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:128px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:155px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:173px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:194px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:214px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:262px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p11_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:279px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:301px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p11_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:321px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p11_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:531px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p11_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:555px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:574px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:593px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:612px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:650px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p11_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:678px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRY/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:704px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRY/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:733px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:753px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755px;top:1073px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417px;top:812px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409px;top:855px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRY/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:423px;top:881px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:905px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:423px;top:931px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:957px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p11_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:978px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448px;top:642px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>C10<br></b></nobr>");
write("</p>");
write("<p id=\"p11_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:773px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p11_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:782px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:805px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B10<br></b></nobr>");
write("</p>");
write("<p id=\"p11_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:800px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p11_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:406px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p11_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:406px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p11_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:861px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p11_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:870px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p11_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:62px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL/<br>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:86px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:434px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:414px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:234px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:340px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:992px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>*5: Without TSA, ACC<br>*6: With TSA, ACC<br>*7: LHD model<br>*8: RHD model<br>*13: Except KQ model<br></b></nobr>");
write("</p>");
write("<p id=\"p11_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:699px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>*13<br></b></nobr>");
write("</p>");
write("<p id=\"p11_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:831px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p11_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752px;top:856px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RELAY <br>CIRCUIT BOARD<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}