with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:927px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:927px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19EB0J10300000000CAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:927px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:164px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>AUDIO UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:73px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>AM/FM ANTENNA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:293px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(GA−NET)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626px;top:353px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B−CAN HI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:139px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>With navigation<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:190px;top:596px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>With premium audio<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:239px;top:765px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SPEAKERS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:836px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>USB JACK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:789px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>With USB JACK CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624px;top:317px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B−CAN LO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:73px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>FM ANTENNA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498px;top:31px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>With premium audio<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:675px;top:386px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B−CAN HI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769px;top:386px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B−CAN LO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:496px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>With Hands Free Telephone<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:244px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>NAVIGATION <br>DISPLAY UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:330px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>NAVIGATION <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:467px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>AUDIO− <br>NAVIGATION <br>SWITCH PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:531px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:510px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>CLIMATE <br>CONTROL <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:244px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>AUDIO <br>REMOTE SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707px;top:330px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>GAUGE <br>CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:638px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>STEREO <br>AMPLIFIER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:712px;top:565px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>AUXILIARY <br>JACK ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:637px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>CENTER <br>DISPLAY UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:619px;top:674px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>CLIMATE <br>CONTROL <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715px;top:438px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>HANDS FREE <br>TELEPHONE <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:752px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:180px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>REARVIEW <br>CAMERA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:89px;top:331px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>RDS−TMC <br>ANTENNA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:831px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>USB ADAPTER <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:401px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>STEREO <br>AMPLIFIER<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}