with(document) {
write("<div id=\"group4\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1055px;\">");
write("<div id=\"rect4\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1055px;\">");
write("<img id=\"img4\" name=\"PrtImgId\" src=\"../img/TL19E00R311000K5351YDAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1055px;border-color:#ffffff\">");
write("<p id=\"p4_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:53px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(6) REAR FLOOR REAR INSULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:4px;top:21px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Unit: mm (in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:819px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(7) REAR WHEELHOUSE INSULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:852px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>43<br>(1.7)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:852px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>73<br>(2.9)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:462px;top:852px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>46<br>(1.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:852px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>73<br>(2.9)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:851px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>43<br>(1.7)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:1009px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>318 (12.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:110px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>R55 (2.2)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:242px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>75 (3.0)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:242px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>137 (5.39)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409px;top:492px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>93 (3.7)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416px;top:671px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>R55 (2.2)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:717px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>112 (4.41)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520px;top:717px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>150 (5.91)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:752px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>262 (10.3)<br></b></nobr>");
write("</p>");
write("</div>");
write("<div id=\"bl4_1\" name=\"prt_bl\" class=\"drag\" from=\"305,970\" to=\"304,942\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp4_1\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:8.69pt;\">(1.9)</span>");
write("</div>");
write("<div id=\"bl4_2\" name=\"prt_bl\" class=\"drag\" from=\"286,969\" to=\"285,953\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp4_2\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:8.69pt;\">49</span>");
write("</div>");
write("<div id=\"bl4_3\" name=\"prt_bl\" class=\"drag\" from=\"644,981\" to=\"643,930\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp4_3\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:8.69pt;\">89 (3.5)</span>");
write("</div>");
write("<div id=\"bl4_4\" name=\"prt_bl\" class=\"drag\" from=\"288,432\" to=\"287,362\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp4_4\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:8.69pt;\">730 (28.7)</span>");
write("</div>");
write("<div id=\"bl4_5\" name=\"prt_bl\" class=\"drag\" from=\"327,432\" to=\"326,361\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp4_5\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:8.69pt;\">536 (21.1)</span>");
write("</div>");
write("<div id=\"bl4_6\" name=\"prt_bl\" class=\"drag\" from=\"359,418\" to=\"358,364\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp4_6\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:8.69pt;\">80 (3.2)</span>");
write("</div>");
write("<div id=\"bl4_7\" name=\"prt_bl\" class=\"drag\" from=\"366,295\" to=\"365,224\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp4_7\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:8.69pt;\">213 (8.39)</span>");
write("</div>");
write("<div id=\"bl4_8\" name=\"prt_bl\" class=\"drag\" from=\"364,564\" to=\"363,495\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp4_8\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:8.69pt;\">243 (9.57)</span>");
write("</div>");
write("<div id=\"bl4_9\" name=\"prt_bl\" class=\"drag\" from=\"652,640\" to=\"651,567\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp4_9\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:8.69pt;\">266 (10.5)</span>");
write("</div>");
write("<div id=\"bl4_10\" name=\"prt_bl\" class=\"drag\" from=\"653,481\" to=\"652,448\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp4_10\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:8.69pt;\">(2.0)</span>");
write("</div>");
write("<div id=\"bl4_11\" name=\"prt_bl\" class=\"drag\" from=\"637,475\" to=\"636,457\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp4_11\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:8.69pt;\">50</span>");
write("</div>");
write("<div id=\"bl4_12\" name=\"prt_bl\" class=\"drag\" from=\"651,422\" to=\"650,353\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp4_12\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:8.69pt;\">129 (5.08)</span>");
write("</div>");
write("<div id=\"bl4_13\" name=\"prt_bl\" class=\"drag\" from=\"636,322\" to=\"635,304\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp4_13\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:8.69pt;\">50</span>");
write("</div>");
write("<div id=\"bl4_14\" name=\"prt_bl\" class=\"drag\" from=\"652,324\" to=\"651,294\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp4_14\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:8.69pt;\">(2.0)</span>");
write("</div>");
write("<div id=\"bl4_15\" name=\"prt_bl\" class=\"drag\" from=\"652,228\" to=\"651,155\" style=\"position:absolute;left:0;top:0;width:0;height:0;overflow:visible;\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<span id=\"tp4_15\" name=\"PrtTpId\" class=\"drag\" style=\"position:relative;font-family:Arial;text-align:left;font-weight:small;font-size:8.69pt;\">235 (9.25)</span>");
write("</div>");
write("</div>");
}