with(document) {
write("<div id=\"group12\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect12\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img12\" name=\"PrtImgId\" src=\"../img/TL19E8BA20300000000DBAD12.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p12_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:192px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>EPS CONTROL UNIT (10)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:192px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>18P CONNECTOR<br>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:807px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SRS UNIT (15)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:794px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SHIFT LOCK<br>SOLENOID (16) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614px;top:781px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>YAW RATE-LATERAL<br>ACCELERATION<br>SENSOR (17)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:400px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>20P CONNECTOR (11)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:388px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>PASSENGER'S UNDER-DASH<br>FUSE/RELAY BOX (H) (12)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:192px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>12P JUNCTION<br>CONNECTOR (9)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:35px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CENTER<br>JUNCTION<br>BOX (B) (1)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162px;top:35px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CENTER<br>JUNCTION<br>BOX (C) (2)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71px;top:179px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CENTER<br>JUNCTION<br>BOX (E) (7)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:35px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CENTER<br>JUNCTION<br>BOX (D) (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:35px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CENTER<br>JUNCTION<br>BOX (G) (4)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:611px;top:35px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CENTER<br>JUNCTION<br>BOX (K) (5)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786px;top:35px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CENTER<br>JUNCTION<br>BOX (J) (6)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:597px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>PASSENGER'S UNDER-DASH<br>FUSE/RELAY BOX (E) (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:597px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>PASSENGER'S UNDER-DASH<br>FUSE/RELAY BOX (A) (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:989px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br>*: Connector with female terminals (single outline): view from terminal side<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}