with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:991px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:991px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E9AH46400055408KBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:991px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:962px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Left side shown; right side is similar.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:54px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A<br></b>Discard.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A<br></b>Discard.<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:32px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:34px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:796px;top:16px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A<br></b>Discard.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:803px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A<br></b>Discard.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:520px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:791px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:819px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:866px;top:530px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:278px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:869px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Clips (C)<br></b>Discaed.<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}