with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:463px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:463px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E00J54460600000CAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:463px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:182px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>HALL IC UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:39px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>MAGNET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:198px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>POWER WINDOW MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:53px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>POWER WINDOW<br>MASTER SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:231px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:303px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>MAGNET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:255px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>IC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:303px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>IC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:256px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:255px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:287px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Period of<br>pulses<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:384px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Period of <br>pulses<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:344px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Position when something <br>is pinched<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:420px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Threshold value for <br>judgment of pinching<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:246px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Period of<br>pulses<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}