with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:975px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:975px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E9AH32500000000CAAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:975px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:106px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ACC unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:608px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Gauge control module<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:90px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Millimeter wave radar<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:377px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Steering angle sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:414px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Wheel speed sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:615px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Cancel switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:651px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Set/decel switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:688px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Res/accel switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:724px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Distance/LKAS switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:780px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Brake pedal position switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:816px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Inhibitor switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:853px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>ETCS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:179px;top:30px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>F-CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544px;top:122px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Adaptive <br>cruise<br>control <br>(ACC) <br>relay<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:253px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LKAS camera<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:187px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>EPS control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:267px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LKAS control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286px;top:492px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Yaw rate-lateral acceleration<br>sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:402px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>Master cylinder pressure sensor<br>Brake actuator<br>Brake fluid pressure sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:402px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>·<br>·<br>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:893px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Output shaft (countershaft)<br>speed sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296px;top:633px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>ACC indicator<br>Multi-information display (MID)<br>Buzzer<br>LKAS indicator<br>EPS indicator<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:633px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>·<br>·<br>·<br>·<br>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:358px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>VSA modulator-control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:572px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Main switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:651px;top:122px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Brake lights<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:840px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}