with(document) {
write("<div id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\">");
write("<div id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/TL19EEB000000000000EBA301.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-93px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:84px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:92px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:85px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:70px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:77px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:92px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:77px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:70px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:70px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:77px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S UNDER-DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:85px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>With ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:92px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Without ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-160px;top:391px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (ELD) (11−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-160px;top:205px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A/F SENSOR 1 (11−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-160px;top:241px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (AFRLY) (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:792px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 18 (15 A)*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:828px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:802px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:749px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A/C CONDENSER FAN MOTOR (37−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:775px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:667px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:630px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 15 (10 A)*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:657px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 16 (7.5 A)*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:666px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:640px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>49<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:603px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 20 (7.5 A)*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:502px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 8 (40 A)*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:613px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A/C COMPRESSOR CLUTCH (37−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:586px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (ACC) (11−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:613px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:586px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:511px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLOWER MOTOR (37−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:511px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:683px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 17 (20 A)*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:183px;top:491px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLOWER MOTOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:227px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:201px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:227px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:201px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:191px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 4 (40 A)*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:586px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:210px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:205px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:31px;top:175px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>38<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:227px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S MICU (15−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:201px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REAR WINDOW DEFOGGER (35−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:228px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>39<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:201px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:512px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>46<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:775px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (FANL) (11−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:776px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>54<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:749px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>53<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:614px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>48<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:587px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>47<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-160px;top:414px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (ELDGND) (11−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-160px;top:768px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (HTRMON) (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-160px;top:804px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (FHETERRLY) (10−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-160px;top:835px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FUEL HEATER (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:179px;top:374px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:277px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:347px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:347px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INERTIA SWITCH (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:369px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:391px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:414px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:369px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (10−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:337px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 5 (20 A)*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:7px;top:749px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:819px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 19 (7.5 A)*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:828px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (VBU) (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:9px;top:718px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>52<br></b></nobr>");
write("</p>");
write("<p id=\"p3_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:321px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p3_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:348px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>41<br></b></nobr>");
write("</p>");
write("<p id=\"p3_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:370px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>42<br></b></nobr>");
write("</p>");
write("<p id=\"p3_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:392px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>43<br></b></nobr>");
write("</p>");
write("<p id=\"p3_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:414px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>44<br></b></nobr>");
write("</p>");
write("<p id=\"p3_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:829px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>56<br></b></nobr>");
write("</p>");
write("<p id=\"p3_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:802px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>55<br></b></nobr>");
write("</p>");
write("<p id=\"p3_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:457px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 7 (20 A)*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:467px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:467px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>45<br></b></nobr>");
write("</p>");
write("<p id=\"p3_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-160px;top:461px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>UNDER−DASH FUSE/RELAY BOX <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-160px;top:567px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>UNDER−DASH FUSE/RELAY BOX <br>(3−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-160px;top:603px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>UNDER−DASH FUSE/RELAY BOX <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-160px;top:714px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RELAY CIRCUIT BOARD <br>(Wiper motor relay circuit) (2−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:713px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A/C <br>CONDENSER <br>FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:564px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A/C COMPRESSOR <br>CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:634px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>UNDER−DASH FUSE/RELAY BOX <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:660px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>UNDER−DASH FUSE/RELAY BOX <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:174px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REAR WINDOW <br>DEFOGGER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:15px;top:148px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 16 (7.5 A)*<sup>2</sup> <br>FUSE <br>(2−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-790px;top:702px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RELAY CIRCUIT BOARD <br>(Fan control relay circuit) (2−A) <br>(Radiator fan relay circuit) (2−A) <br>(ISV control relay circuit) (2−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-502px;top:143px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PGM−FI <br>MAIN RELAY 2 <br>(SOL) <br>(Via relay <br>circuit board) <br>(2−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-502px;top:689px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PGM−FI <br>MAIN RELAY 2 <br>(SOL) <br>(Via relay <br>circuit board) <br>(2−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:290px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PGM−FI MAIN <br>RELAY 1 <br>(ECU)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162px;top:394px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PGM−FI MAIN <br>RELAY 2 (SOL) <br>(1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:346px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PGM−FI MAIN RELAY 3 <br>(FUEL PUMP) (2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:249px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PGM−FI MAIN <br>RELAY 2 (SOL) <br>(1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:800px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RELAY CIRCUIT BOARD <br>(ISV control relay circuit) (2−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-160px;top:501px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>POWER TAILGATE CONTROL UNIT <br>(+B PTG MTR) (45−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-160px;top:643px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RELAY CIRCUIT BOARD <br>(Radiator fan relay circuit) (2−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:465px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>POWER TAILGATE CONTROL UNIT <br>(+B CLOSER MTR) (45−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:390px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FUEL RAIL PRESSURE CONTROL VALVE 2 <br>(Built into the fuel rail) (10−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:412px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FUEL RAIL PRESSURE CONTROL VALVE <br>(Built into the high pressure fuel pump) (10−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:210px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CONDENSERS*<sup>5</sup> (35−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:99px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:106px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:99px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:106px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:99px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4−door<br></b></nobr>");
write("</p>");
write("<p id=\"p3_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:106px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5−door<br></b></nobr>");
write("</p>");
write("<p id=\"p3_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TCM RELAY (12−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:693px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>51<br></b></nobr>");
write("</p>");
write("<p id=\"p3_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:648px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 2−6<br>(SUB FAN) (30 A)*<sup>1</sup><br>FUSE (1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77px;top:675px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}