with(document) {
write("<div id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:554px;\">");
write("<div id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:554px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/TL19EAQJ32133100000EAAD91.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:554px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:438px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:524px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:301px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:301px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:635px;top:524px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:438px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:592px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>E10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:180px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:176px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:751px;top:176px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:751px;top:180px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>E2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:835px;top:301px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:841px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>E12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:227px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>IPD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:227px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>IPD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:227px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>IPD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:176px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:180px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:843px;top:179px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:205px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583px;top:408px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LO (35 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575px;top:416px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643px;top:416px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:592px;top:353px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643px;top:353px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:378px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HID UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:380px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(60 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:376px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HIGH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:533px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(With HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:776px;top:533px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Without HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775px;top:376px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HIGH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775px;top:380px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(60 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769px;top:353px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769px;top:416px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:438px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761px;top:524px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:735px;top:380px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(55 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:735px;top:376px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LOW<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:524px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:438px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:416px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:353px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:793px;top:153px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PASSENGER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:675px;top:188px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PASSENGER'S MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839px;top:16px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839px;top:20px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:847px;top:20px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:851px;top:20px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Without automatic lighting system<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:851px;top:16px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>With automatic lighting system<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:847px;top:16px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:585px;top:129px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:95px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:592px;top:153px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837px;top:324px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600px;top:417px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT<br>HEADLIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:417px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT<br>HEADLIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820px;top:337px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DAYTIME RUNNING <br>LIGHTS RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:64px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 3−3 <br>(AS LT MAIN)<br>(50 A) FUSE <br>(UNDER−HOOD <br>FUSE/RELAY <br>BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:851px;top:25px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5−door<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838px;top:25px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>[     ]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:847px;top:25px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:842px;top:260px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 6 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:864px;top:301px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:861px;top:337px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DASH<br>LIGHTS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:164px;top:346px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:386px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:369px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:386px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:346px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:524px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G901<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:524px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G901<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107px;top:346px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82px;top:438px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107px;top:438px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:176px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 27<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:180px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:301px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:438px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:524px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G901<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:386px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>D11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222px;top:438px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:524px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G302<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:369px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:386px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82px;top:226px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>IPD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:179px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:205px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:164px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:25px;top:153px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:188px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DRIVER'S MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:164px;top:346px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222px;top:346px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:169px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 29 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224px;top:186px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224px;top:229px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:229px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:229px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:201px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>H/L<br></b></nobr>");
write("</p>");
write("<p id=\"p2_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:95px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:524px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G505<br></b></nobr>");
write("</p>");
write("<p id=\"p2_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A36<br></b></nobr>");
write("</p>");
write("<p id=\"p2_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:298px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:256px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:524px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G505<br></b></nobr>");
write("</p>");
write("<p id=\"p2_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A37<br></b></nobr>");
write("</p>");
write("<p id=\"p2_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:298px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:256px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:524px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p2_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>E15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:298px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:256px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:256px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:298px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>E16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:524px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p2_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:188px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PASSENGER'S MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:425px;top:196px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392px;top:196px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>VBU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:196px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BACK−UP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:368px;top:153px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A17<br></b></nobr>");
write("</p>");
write("<p id=\"p2_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:129px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:95px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p2_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396px;top:95px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p2_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:425px;top:129px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:129px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:153px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:153px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A35<br></b></nobr>");
write("</p>");
write("<p id=\"p2_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:184px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p2_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:346px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:386px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:369px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:524px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p2_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:438px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:304px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:129px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311px;top:153px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A24<br></b></nobr>");
write("</p>");
write("<p id=\"p2_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:245px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:245px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:245px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:438px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:524px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G901<br></b></nobr>");
write("</p>");
write("<p id=\"p2_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201px;top:369px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201px;top:386px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:346px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136px;top:438px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:524px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G901<br></b></nobr>");
write("</p>");
write("<p id=\"p2_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144px;top:369px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144px;top:386px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136px;top:346px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:394px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LICENSE  <br>PLATE <br>LIGHTS <br>(5 W x 2)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:394px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT <br>TAILLIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:394px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT <br>TAILLIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:393px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT <br>FRONT <br>POSITION <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:143px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PASSENGER'S <br>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:69px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DRIVER'S MICU <br>(DRIVER'S <br>UNDER−DASH <br>FUSE/RELAY <br>BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:69px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 15 (10 A) <br>FUSE <br>(UNDER−HOOD <br>FUSE/RELAY <br>BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417px;top:64px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 5 (7.5 A) <br>FUSE <br>(DRIVER'S <br>UNDER−DASH <br>FUSE/RELAY <br>BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:254px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DAYTIME <br>RUNNING <br>LIGHTS <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:162px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PASSENGER'S <br>UNDER−DASH <br>FUSE/RELAY <br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:393px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT <br>FRONT <br>POSITION <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:393px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT <br>INNER <br>TAILLIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:393px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT <br>INNER <br>TAILLIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144px;top:532px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(5−door)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201px;top:532px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(5−door)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:364px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:369px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>[1]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:364px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:369px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>[1]<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}