with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:991px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:991px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E00R51100000000YDAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:991px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:650px;top:911px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TUNNEL STIFFENER A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624px;top:733px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:799px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:766px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:549px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD <br>LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801px;top:527px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INSIDE SILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:880px;top:212px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INNER<br>LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765px;top:195px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INSIDE SILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:868px;top:266px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>JACK UP<br>BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:817px;top:152px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD <br>LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828px;top:57px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT PILLAR<br>INNER LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:700px;top:55px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD <br>UPPER<br>SIDE MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:54px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD<br>UPPER SIDE<br>MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:667px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD UPPER<br>CROSS-MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT PILLAR<br>INNER UPPER/LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:63px;top:18px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT PILLAR<br>INNER LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:75px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD UPPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:192px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD UPPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:282px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD<br>LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:126px;top:320px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>WINDSHIELD<br>LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:456px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD UPPER<br>CROSS-MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:525px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD UPPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:15px;top:714px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD<br>LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98px;top:731px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SIDE FRAME END<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:753px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:848px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:848px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600px;top:947px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD LOWER<br>CENTER EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48px;top:919px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD LOWER<br>CENTER EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:12px;top:320px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD<br>UPPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:440px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SIDE SILL<br>REINFORCEMENT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:492px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INNER LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830px;top:600px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INSIDE SILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739px;top:655px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INSIDE SILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:829px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:931px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:951px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD LOWER<br>CENTER EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:952px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD<br>LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:833px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13px;top:641px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD<br>UPPER<br>CROSS-<br>MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:497px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>WINDSHIELD LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:423px;top:66px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>WINDSHIELD<br>LOWER<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD UPPER<br>SIDE MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:308px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INSIDE SILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:886px;top:320px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INNER<br>LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:879px;top:377px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>JACK UP<br>BRACKET<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}