with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:895px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:895px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E00J32100017101FHAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:895px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:29px;top:299px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>[  ]: KQ model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:585px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>[  ]: KQ model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506px;top:617px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Front/rear fog light switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:641px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Terminal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:524px;top:667px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563px;top:704px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:755px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REAR*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:807px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT/REAR*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688px;top:653px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 [11]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:796px;top:653px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:870px;top:653px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>12 [7]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498px;top:846px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>[  ]: KQ model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:616px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Turn signal switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:640px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Terminal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:666px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103px;top:704px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:755px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>NEUTRAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:806px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:652px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1 [6]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:653px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>2 [5]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:846px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>[  ]: KQ model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:653px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>12 [7]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:355px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Terminal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:380px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58px;top:456px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Headlight switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:367px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>9 [10]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:544px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Passing switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:267px;top:406px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:456px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LOW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:494px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HIGH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:534px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:559px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575px;top:368px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>10 [9]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:862px;top:367px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>11 [8]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:330px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Light switch (automatic lighting system)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:367px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>4 [3]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:367px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 [1]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:367px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>12 [7]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:42px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Terminal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:57px;top:68px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58px;top:155px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Headlight switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:55px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>9 [10]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:257px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Passing switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:267px;top:93px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:170px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LOW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:208px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HIGH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:247px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:271px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:576px;top:55px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>10 [9]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:862px;top:55px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>11 [8]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Light switch (automatic lighting system)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:55px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>4 [3]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:55px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 [1]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:55px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>12 [7]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:144px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>AUTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498px;top:878px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>*: Except KQ model<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}