with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:288px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:288px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E00J36100000000FEAD16.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:288px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:38px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>Return<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:38px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>Display<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:80px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>Connection<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:80px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>OK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:103px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>ROM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:103px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>OK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:126px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>RAM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:126px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>OK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:149px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>Version<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:149px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>099100<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}