with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:952px; height:623px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:952px;height:623px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E00D14300014781LDAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:952px;height:623px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329px;top:110px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>RESERVOIR CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:63px;top:205px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>3 N·m <br>(0.3 kgf·m, <br>2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329px;top:158px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>RESERVOIR SEAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329px;top:204px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>STRAINER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:267px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>RESERVOIR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:329px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>GROMMET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:476px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>STOP PIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:562px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>MASTER CYLINDER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451px;top:579px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PISTON <br>CUPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:325px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PRIMARY<br>PISTON<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:305px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>SECONDARY<br>PISTON<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612px;top:284px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>(PINK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:485px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>CIRCLIP<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:272px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PISTON GUIDE<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:845px;top:309px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>(BEIGE)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:846px;top:245px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ROD SEAL<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:680px;top:531px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>SECONDARY CUP<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:596px;top:577px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:537px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>(BEIGE)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:27px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>: Rubber grease<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:61px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>: Silicone grease<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}