with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:959px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:959px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E00D14300014711LAAD13.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:959px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:336px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SEALING WASHERS<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:485px;top:93px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BLEED SCREW<br>9 N·m <br>(0.9 kgf·m, 7 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:458px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1.0 mm<br>23 N·m <br>(2.3 kgf·m, <br>17 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:509px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PISTON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:827px;top:496px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PISTON BOOT<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:493px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PISTON SEAL<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:485px;top:458px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CALIPER BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:836px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OUTER PAD SHIM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628px;top:867px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BRAKE PADS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:843px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>WEAR INDICATOR<br></b>Install inner brake pad <br>with its wear indicator <br>downward.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:857px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PIN BOOT<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:858px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CALIPER PIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:386px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CALIPER PIN A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:418px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>12 x 1.25 mm<br>108 N·m <br>(11.0 kgf·m, <br>79.6 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:806px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CALIPER BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:234px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BANJO BOLT<br>35 N·m <br>(3.6 kgf·m, <br>26 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:203px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BRAKE HOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:174px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ARM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:317px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>23 N·m <br>(2.3 kgf·m, <br>17 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:559px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(CLEAR)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:827px;top:562px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(PINK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:5px;top:564px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CALIPER <br>PIN B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:611px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PAD RETAINERS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:923px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(ORANGE)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:444px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(ORANGE)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:601px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(ORANGE)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:27px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>: Rubber grease<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:62px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>: Silicone grease<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}