with(document) {
write("<div id=\"group9\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\">");
write("<div id=\"rect9\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img9\" name=\"PrtImgId\" src=\"../img/TL19E7QJ54260400000EAAD09.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p9_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:33px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p9_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:146px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left front fog light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:144px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:194px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Driver's MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:183px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:915px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 31 (Not used)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:858px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 30 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:873px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Driver's MICU (H/L LO)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:862px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:801px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 29 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:748px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:759px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Driver's MICU (H/L HI)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:743px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 28 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:509px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p9_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:523px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>License plate lights<br></b></nobr>");
write("</p>");
write("<p id=\"p9_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:495px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p9_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:495px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p9_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:430px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Driver's MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:419px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:129px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 26 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:415px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 27 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:144px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p9_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:102px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p9_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:480px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left front position light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:480px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p9_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:547px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Without automatic lighting)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:362px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(With automatic lighting)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:302px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>IPD<br></b></nobr>");
write("</p>");
write("<p id=\"p9_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:219px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Without automatic lighting)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:339px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left front fog light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:337px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:733px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(With automatic lighting)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:630px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>IPD<br></b></nobr>");
write("</p>");
write("<p id=\"p9_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:663px;top:695px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p9_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:663px;top:709px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>License plate lights<br></b></nobr>");
write("</p>");
write("<p id=\"p9_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:680px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p9_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:663px;top:680px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p9_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:663px;top:666px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left front position light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:666px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p9_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:816px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:663px;top:816px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Daytime running lights relay<br></b></nobr>");
write("</p>");
write("<p id=\"p9_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:663px;top:830px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Daytime running lights relay<br></b></nobr>");
write("</p>");
write("<p id=\"p9_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:106px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>FRONT FOG LIGHT <br>RELAY CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:399px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>TAILLIGHT <br>RELAY CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48px;top:48px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>No. 3−5 (DR LT MAIN) <br>(40 A) FUSE <br>(UNDER−HOOD <br>FUSE/RELAY BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:297px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>DRIVER'S <br>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:626px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>DRIVER'S <br>MICU<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}