with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:950px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:950px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E9AH46400000000AAAD23.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:32px;font-weight:normal;font-size:6.37pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582px;top:32px;font-weight:normal;font-size:6.37pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:537px;font-weight:normal;font-size:6.37pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:65px;font-weight:normal;font-size:6.37pt;\">");
write("<nobr><b>CABLE REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:144px;font-weight:normal;font-size:6.37pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:78px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>DASHBOARD <br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:430px;top:135px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>DASHBOARD <br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:189px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>DASHBOARD <br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:246px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>DASHBOARD <br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:246px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>LEFT ENGINE COMPARTMENT <br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:464px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>SRS <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:60px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>DRIVER'S <br>AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:111px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:169px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>RIGHT FRONT <br>IMPACT <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:226px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>LEFT FRONT <br>IMPACT <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:283px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>RIGHT SIDE <br>SEAT BELT <br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:469px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>RIGHT SIDE <br>AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:692px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>LEFT SIDE <br>IMPACT SENSOR <br>(FIRST)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:806px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>RIGHT <br>SIDE CURTAIN <br>AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:189px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>RIGHT ENGINE COMPARTMENT <br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:733px;top:640px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>LEFT SIDE <br>AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:520px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>RIGHT SIDE <br>IMPACT SENSOR <br>(FIRST)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:884px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>SRS FLOOR <br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:749px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>LEFT <br>SIDE IMPACT <br>SENSOR (SECOND)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:863px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>LEFT <br>SIDE CURTAIN <br>AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:577px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>RIGHT <br>SIDE IMPACT <br>SENSOR (SECOND)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:403px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>LEFT SIDE <br>SEAT BELT <br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:337px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>LEFT SIDE <br>SEAT BELT <br>OUTER LAP <br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:827px;font-weight:normal;font-size:6.44pt;\">");
write("<nobr><b>SRS FLOOR <br>SUBHARNESS<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}