with(document) {
write("<div id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1039px;\">");
write("<div id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1039px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/TL19E4AE34116317081LAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1039px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:294px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BLEEDER SCREW CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:192px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ROLL PINS<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BLEEDER SCREW<br>8 N·m<br>(0.8 kgf·m, 6 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560px;top:174px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CLUTCH LINE<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:340px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Removal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:340px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Installation<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786px;top:21px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PISTON CUP<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:440px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SLAVE CYLINDER PISTON<br></b>Check for wear and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:513px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SLAVE CYLINDER SPRING<br></b>Install with small and<br>facing piston.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:596px;top:574px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BOOT<br></b>Check that it is fitted securely<br>over the cylinder body.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:981px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(RUBBER)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:610px;top:1009px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(MOLIBDENUM)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:753px;top:736px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PUSHROD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:696px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(RUBBER)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785px;top:85px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(RUBBER)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58px;top:68px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SLAVE CYLINDER BODY<br></b>Check the cylinder wall<br>for scoring and wear.<br></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:77px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:142px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(RUBBER)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}