with(document) {
write("<div id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\">");
write("<div id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1023px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/TL19EC1A20300000000DBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628px;top:30px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FRP <br>CONTROL<br>VALVE (5)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:202px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>INTAKE SHUTTER<br>VALVE (8)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:201px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>MAP SENSOR/<br>IAT SENSOR 2<br>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:188px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX (B) (9)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:474px;top:30px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>TURBOCHARGER<br>BOOST CONTROL<br>SOLENOID VALVE<br>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:356px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>31P CONNECTOR (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:42px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>IMRC<br>VALVE (2)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:793px;top:356px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>GLOW PLUG<br>CONTROL MODULE<br>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:824px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECT<br>SENSOR 2 <br>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:343px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FUEL FILTER <br>WATER LEVEL<br>SWITCH (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:826px;top:214px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FUEL HEATER<br>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563px;top:189px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX (C) (10)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:727px;top:215px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ELD (11)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:813px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>TEST<br>TACHOMETER<br>CONNECTOR <br>(23)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:121px;top:565px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECM CONNECTOR No. 2<br>(58P) (18)*<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:17px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>EGR COOLER<br>BYPASS CONTROL <br>SOLENOID<br>VALVE (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:17px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>TURBOCHARGER<br>BOOST CONTROL<br>VALVE POSITION<br>SENSOR (1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:825px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECT <br>SENSOR 1<br>(24)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48px;top:812px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>REVERSE LOCK<br>SOLENOID <br>VALVE (20)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:812px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>OUTPUT SHAFT<br>(COUNTERSHAFT)<br>SPEED SENSOR <br>(21) <br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:356px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>MAP SENSOR/<br>IAT SENSOR 1<br>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:344px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FUEL <br>TEMPERATURE<br>SENSOR (15)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:762px;top:56px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>EGR VALVE (6)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672px;top:837px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>24P JUNCTION CONNECTOR (25)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:565px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECM CONNECTOR No. 1<br>(96P) (19)*<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:949px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br>*: Connector with female terminals (single outline): view from terminal side<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}