with(document) {
write("<div id=\"group10\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1085px;\">");
write("<div id=\"rect10\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1085px;\">");
write("<img id=\"img10\" name=\"PrtImgId\" src=\"../img/TL19EC0J54230100000EAAD10.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1085px;border-color:#ffffff\">");
write("<p id=\"p10_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58px;top:444px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p10_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:443px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:444px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p10_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:230px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p10_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:230px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:144px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:187px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:144px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p10_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:187px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p10_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:47px;top:387px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G901<br></b></nobr>");
write("</p>");
write("<p id=\"p10_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:273px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p10_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:273px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:315px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:315px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p10_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:145px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left brake light/taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p10_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:159px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p10_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:202px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right rear turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p10_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:187px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right brake light/taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p10_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:230px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Trunk lid latch switch/Trunk lid release actuator<br></b></nobr>");
write("</p>");
write("<p id=\"p10_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:245px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Trunk lid outer handle switch<br></b></nobr>");
write("</p>");
write("<p id=\"p10_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:273px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>License plate lights<br></b></nobr>");
write("</p>");
write("<p id=\"p10_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:316px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right back−up light<br></b></nobr>");
write("</p>");
write("<p id=\"p10_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:330px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear fog light<br></b></nobr>");
write("</p>");
write("<p id=\"p10_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:30px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>W<br></b></nobr>");
write("</p>");
write("<p id=\"p10_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:30px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear window defogger (−) terminal<br></b></nobr>");
write("</p>");
write("<p id=\"p10_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:30px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:47px;top:87px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G801<br></b></nobr>");
write("</p>");
write("<p id=\"p10_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55px;top:465px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>W<br></b></nobr>");
write("</p>");
write("<p id=\"p10_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:464px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:465px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear window defogger ground wire<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}