with(document) {
write("<div id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1085px;\">");
write("<div id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1085px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/TL19EC0J54230100000EAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1085px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:662px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:663px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right engine compartment wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224px;top:85px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:85px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:85px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Passenger's MICU (PG)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:320px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:156px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:156px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:157px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right headlight (High beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:192px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:192px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:227px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Headlight washer motor<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:227px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:227px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:263px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:263px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:264px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right front fog light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:399px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:399px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:363px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:363px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:456px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G202<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:663px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:207px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right front position light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:192px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right front turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:120px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:120px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:85px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:85px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:121px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Passenger's MICU (SG)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502px;top:73px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502px;top:109px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:363px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>VSA modulator−control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:399px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>VSA modulator−control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:535px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>EPS control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:592px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G203<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:535px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:535px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:171px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right headlight (Low beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412px;top:28px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>PASSENGER'S <br>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:277px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>Rigt headlight leveling motor <br>(Without HID)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}