with(document) {
write("<div id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\">");
write("<div id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/TL19EGP000000000000EBA345.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-93px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>45<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:71px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:78px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:77px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:70px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:78px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:70px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:369px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-18px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-63px;top:369px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-18px;top:369px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:154px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(With ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-19px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-64px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-182px;top:303px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E−PRETENSIONER UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-63px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-25px;top:795px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G703<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-2px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:33px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185px;top:387px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:387px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:387px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375px;top:387px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:369px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:387px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:478px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:387px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:387px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B17<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B16<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-93px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B18<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B15<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B10<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:425px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B11<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B24<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B25<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:464px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B38<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:464px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B39<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:464px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B37<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:464px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B36<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:531px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:464px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:677px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:677px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:8px;top:677px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-53px;top:677px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:425px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:336px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:336px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416px;top:336px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:336px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:336px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:336px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:336px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:336px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:336px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:336px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:336px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:318px;top:336px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-9px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-53px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:318px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-9px;top:318px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A14<br></b></nobr>");
write("</p>");
write("<p id=\"p3_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-53px;top:318px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A13<br></b></nobr>");
write("</p>");
write("<p id=\"p3_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-53px;top:287px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-9px;top:287px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:287px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:188px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:99px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:444px;top:99px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CAN line<br></b></nobr>");
write("</p>");
write("<p id=\"p3_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:108px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:444px;top:108px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Other communication line<br></b></nobr>");
write("</p>");
write("<p id=\"p3_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:85px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:85px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:47px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:462px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517px;top:369px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:486px;top:387px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:387px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:387px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:318px;top:387px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:387px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:387px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:387px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100px;top:369px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:215px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>167<br></b></nobr>");
write("</p>");
write("<p id=\"p3_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-18px;top:215px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>383<br></b></nobr>");
write("</p>");
write("<p id=\"p3_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-62px;top:215px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>384<br></b></nobr>");
write("</p>");
write("<p id=\"p3_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RLBC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RCBC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LRP+<br></b></nobr>");
write("</p>");
write("<p id=\"p3_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LRP−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LLP−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LLP+<br></b></nobr>");
write("</p>");
write("<p id=\"p3_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RRP+<br></b></nobr>");
write("</p>");
write("<p id=\"p3_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RRP−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LSA+<br></b></nobr>");
write("</p>");
write("<p id=\"p3_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LSA−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:371px;top:478px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RBS1−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:478px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RBS1+<br></b></nobr>");
write("</p>");
write("<p id=\"p3_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:478px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LBS1−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:478px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LBS1+<br></b></nobr>");
write("</p>");
write("<p id=\"p3_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:478px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ODS<br></b></nobr>");
write("</p>");
write("<p id=\"p3_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RSA+<br></b></nobr>");
write("</p>");
write("<p id=\"p3_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RSA−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LCA1+<br></b></nobr>");
write("</p>");
write("<p id=\"p3_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LCA1−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RCA1+<br></b></nobr>");
write("</p>");
write("<p id=\"p3_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:518px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RCA1−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-64px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:444px;top:117px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Shielding<br></b></nobr>");
write("</p>");
write("<p id=\"p3_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:117px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:795px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G751<br></b></nobr>");
write("</p>");
write("<p id=\"p3_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-342px;top:188px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 1 (7.5 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-226px;top:457px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT SIDE <br>E−PRETENSIONER MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:457px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT SIDE <br>E−PRETENSIONER MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-162px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HALL <br>IC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-169px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT SIDE <br>SEAT BELT <br>BUCKLE <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-302px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT SIDE <br>SEAT BELT <br>BUCKLE <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-381px;top:691px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>SEAT SITTING <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-93px;top:691px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REAR RIGHT <br>SEAT BELT <br>BUCKLE <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:20px;top:691px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REAR CENTER/ <br>REAR LEFT <br>SEAT BELT <br>BUCKLE SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:308px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT SIDE <br>IMPACT SENSOR (FIRST)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286px;top:301px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT SIDE  <br>IMPACT <br>SENSOR <br>(SECOND)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:308px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT SIDE <br>IMPACT SENSOR (FIRST)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:301px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT SIDE  <br>IMPACT <br>SENSOR <br>(SECOND)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:722px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT SIDE <br>SEAT BELT <br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p3_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:722px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT SIDE <br>OUTER LAP <br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p3_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:722px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT SIDE <br>SEAT BELT <br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p3_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:722px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT SIDE <br>AIRBAG <br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:722px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT SIDE <br>AIRBAG <br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422px;top:721px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT SIDE <br>CURTAIN <br>AIRBAG <br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:722px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT SIDE <br>CURTAIN <br>AIRBAG <br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-470px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT SIDE <br>SEAT BELT <br>BUCKLE <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-231px;top:188px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 20 (30 A) <br>FUSE <br>(4−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:188px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 21 (30 A) <br>FUSE <br>(4−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:77px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Wire colors may be substituted <br>for SRS circuits<br></b></nobr>");
write("</p>");
write("<p id=\"p3_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-62px;top:191px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GAUGE CONTROL <br>MODULE (14−A)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}